import type { SupabaseClient } from "@supabase/supabase-js";
import { describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

import { saveWorkspaceAiSettings } from "./ai-settings";

const allowedModels = ["mistral-small-latest", "mistral-large-latest"];

describe("saveWorkspaceAiSettings", () => {
  it("validates before touching the workspace-scoped table", async () => {
    const from = vi.fn();
    const supabase = { from } as unknown as SupabaseClient;

    await expect(
      saveWorkspaceAiSettings(
        supabase,
        "workspace-1",
        {
          tone: "professional",
          language: "de",
          signature: "",
          debounceSeconds: 601,
          model: "unknown-model",
          autoGenerateDm: true,
        },
        allowedModels,
      ),
    ).resolves.toEqual({
      ok: false,
      error: "Дебаунс должен быть целым числом от 0 до 600 секунд.",
    });
    expect(from).not.toHaveBeenCalled();
  });

  it("upserts every setting with the trusted workspace id", async () => {
    const single = vi.fn().mockResolvedValue({
      data: { id: "settings-1", workspace_id: "workspace-1" },
      error: null,
    });
    const select = vi.fn(() => ({ single }));
    const upsert = vi.fn(() => ({ select }));
    const from = vi.fn(() => ({ upsert }));
    const supabase = { from } as unknown as SupabaseClient;

    const result = await saveWorkspaceAiSettings(
      supabase,
      "workspace-1",
      {
        tone: " friendly ",
        language: " de ",
        signature: " Viele Grüße ",
        debounceSeconds: 45,
        model: "mistral-small-latest",
        autoGenerateDm: false,
      },
      allowedModels,
    );

    expect(result.ok).toBe(true);
    expect(from).toHaveBeenCalledWith("ai_settings");
    expect(upsert).toHaveBeenCalledWith(
      expect.objectContaining({
        workspace_id: "workspace-1",
        tone: "friendly",
        language: "de",
        signature: "Viele Grüße",
        debounce_seconds: 45,
        model: "mistral-small-latest",
        auto_generate_dm: false,
      }),
      { onConflict: "workspace_id" },
    );
  });
});
