import type { SupabaseClient } from "@supabase/supabase-js";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  revalidatePath: vi.fn(),
  getAuthenticatedUser: vi.fn(),
  getCurrentWorkspace: vi.fn(),
  createServerSupabaseClient: vi.fn(),
}));

vi.mock("server-only", () => ({}));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath }));
vi.mock("@/lib/db/workspace", () => ({
  getAuthenticatedUser: mocks.getAuthenticatedUser,
  getCurrentWorkspace: mocks.getCurrentWorkspace,
}));
vi.mock("@/lib/db/server", () => ({
  createServerSupabaseClient: mocks.createServerSupabaseClient,
}));

import { saveAiSettingsAction } from "./actions";

function createSupabaseClient() {
  const single = vi.fn().mockResolvedValue({
    data: {
      id: "settings-1",
      workspace_id: "workspace-1",
      tone: "professional",
      language: "de",
      signature: "",
      debounce_seconds: 600,
      model: "mistral-small-latest",
      auto_generate_dm: true,
      auto_generate_comments: false,
    },
    error: null,
  });
  const select = vi.fn(() => ({ single }));
  const upsert = vi.fn(() => ({ select }));
  const from = vi.fn(() => ({ upsert }));

  return {
    client: { from } as unknown as SupabaseClient,
    from,
    upsert,
  };
}

beforeEach(() => {
  vi.stubEnv("MISTRAL_API_KEY", "mistral-secret");
  vi.stubEnv("OPENROUTER_API_KEY", "openrouter-secret");
  vi.stubEnv("OPENROUTER_MODEL", "vendor/fallback-model");
  mocks.getAuthenticatedUser.mockResolvedValue({ id: "user-1" });
  mocks.getCurrentWorkspace.mockResolvedValue({ id: "workspace-1" });
  mocks.revalidatePath.mockReset();
});

describe("saveAiSettingsAction validation", () => {
  it("accepts the debounce upper boundary and a configured Mistral model", async () => {
    const supabase = createSupabaseClient();
    mocks.createServerSupabaseClient.mockResolvedValue(supabase.client);

    const result = await saveAiSettingsAction({
      tone: "professional",
      language: "de",
      signature: "",
      debounceSeconds: 600,
      model: "mistral-small-latest",
      autoGenerateDm: true,
      autoGenerateComments: false,
    });

    expect(result.ok).toBe(true);
    expect(supabase.upsert).toHaveBeenCalledWith(
      expect.objectContaining({ workspace_id: "workspace-1", debounce_seconds: 600 }),
      { onConflict: "workspace_id" },
    );
    expect(mocks.revalidatePath).toHaveBeenCalledWith("/settings");
  });

  it("rejects an unknown model before querying ai_settings", async () => {
    const supabase = createSupabaseClient();
    mocks.createServerSupabaseClient.mockResolvedValue(supabase.client);

    const result = await saveAiSettingsAction({
      tone: "professional",
      language: "de",
      signature: "",
      debounceSeconds: 60,
      model: "vendor/fallback-model",
      autoGenerateDm: true,
      autoGenerateComments: false,
    });

    expect(result).toEqual({ ok: false, error: "Выбранная модель недоступна." });
    expect(supabase.from).not.toHaveBeenCalled();
  });
});
