"use client";

import { useMemo, useState, useTransition, type FormEvent } from "react";

import type { AiModelOption } from "@/lib/ai/config";
import {
  AI_DEBOUNCE_MAX_SECONDS,
  AI_DEBOUNCE_MIN_SECONDS,
  AI_LANGUAGE_MAX_LENGTH,
  AI_SIGNATURE_MAX_LENGTH,
  AI_TONE_MAX_LENGTH,
  validateAiSettingsInput,
  type AiSettingsInput,
} from "@/lib/ai/settings";

import uiStyles from "../../_components/ui.module.css";
import styles from "../settings.module.css";
import { saveAiSettingsAction } from "./actions";

export type AiSettingsFormValue = AiSettingsInput;

const TONE_OPTIONS = [
  { value: "professional", label: "Профессиональный" },
  { value: "friendly", label: "Дружелюбный" },
  { value: "neutral", label: "Нейтральный" },
  { value: "formal", label: "Формальный" },
] as const;

const LANGUAGE_OPTIONS = [
  { value: "auto", label: "Как у клиента" },
  { value: "de", label: "Немецкий" },
  { value: "en", label: "Английский" },
  { value: "ru", label: "Русский" },
] as const;

function withCurrentOption(
  options: readonly { value: string; label: string }[],
  current: string,
) {
  return options.some((option) => option.value === current)
    ? options
    : [{ value: current, label: current }, ...options];
}

export function AiSettingsForm({
  initialValue,
  modelOptions,
}: {
  initialValue: AiSettingsFormValue;
  modelOptions: AiModelOption[];
}) {
  const [value, setValue] = useState(initialValue);
  const [savedValue, setSavedValue] = useState(initialValue);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [isPending, startTransition] = useTransition();
  const toneOptions = useMemo(
    () => withCurrentOption(TONE_OPTIONS, value.tone),
    [value.tone],
  );
  const languageOptions = useMemo(
    () => withCurrentOption(LANGUAGE_OPTIONS, value.language),
    [value.language],
  );
  const visibleModelOptions = useMemo(
    () =>
      value.model && !modelOptions.some((option) => option.value === value.model)
        ? [
            {
              value: value.model,
              label: `${value.model} (недоступна в текущем конфиге)`,
            },
            ...modelOptions,
          ]
        : modelOptions,
    [modelOptions, value.model],
  );
  const isDirty = JSON.stringify(value) !== JSON.stringify(savedValue);

  function update<K extends keyof AiSettingsFormValue>(
    key: K,
    next: AiSettingsFormValue[K],
  ) {
    setValue((current) => ({ ...current, [key]: next }));
    setError(null);
    setSaved(false);
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const validation = validateAiSettingsInput(
      value,
      modelOptions.map((option) => option.value),
    );

    if (!validation.ok) {
      setSaved(false);
      setError(validation.error);
      return;
    }

    setError(null);
    setSaved(false);
    startTransition(async () => {
      const result = await saveAiSettingsAction(validation.data);

      if (!result.ok) {
        setError(result.error);
        return;
      }

      const persisted: AiSettingsFormValue = {
        tone: result.data.tone,
        language: result.data.language,
        signature: result.data.signature,
        debounceSeconds: result.data.debounce_seconds,
        model: result.data.model,
        autoGenerateDm: result.data.auto_generate_dm,
      };
      setValue(persisted);
      setSavedValue(persisted);
      setSaved(true);
    });
  }

  return (
    <form className={styles.aiForm} onSubmit={handleSubmit}>
      <div className={`${uiStyles.card} ${uiStyles.cardStack}`}>
        <div className={uiStyles.field}>
          <label htmlFor="ai-tone">Тон ответов</label>
          <select
            id="ai-tone"
            value={value.tone}
            onChange={(event) => update("tone", event.target.value)}
            disabled={isPending}
          >
            {toneOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <span className={styles.fieldHint}>До {AI_TONE_MAX_LENGTH} символов.</span>
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-language">Язык ответов</label>
          <select
            id="ai-language"
            value={value.language}
            onChange={(event) => update("language", event.target.value)}
            disabled={isPending}
          >
            {languageOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <span className={styles.fieldHint}>
            До {AI_LANGUAGE_MAX_LENGTH} символов.
          </span>
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-signature">Подпись</label>
          <input
            id="ai-signature"
            type="text"
            value={value.signature}
            onChange={(event) => update("signature", event.target.value)}
            maxLength={AI_SIGNATURE_MAX_LENGTH}
            disabled={isPending}
          />
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-model">Модель</label>
          <select
            id="ai-model"
            value={value.model}
            onChange={(event) => update("model", event.target.value)}
            disabled={isPending}
          >
            <option value="">Авто — модель из конфигурации</option>
            {visibleModelOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-debounce">Пауза перед генерацией</label>
          <div className={styles.aiDebounceField}>
            <input
              id="ai-debounce"
              type="number"
              min={AI_DEBOUNCE_MIN_SECONDS}
              max={AI_DEBOUNCE_MAX_SECONDS}
              step={1}
              value={value.debounceSeconds}
              onChange={(event) =>
                update("debounceSeconds", event.target.valueAsNumber)
              }
              disabled={isPending}
            />
            <span>секунд</span>
          </div>
          <span className={styles.fieldHint}>
            Целое число от {AI_DEBOUNCE_MIN_SECONDS} до{" "}
            {AI_DEBOUNCE_MAX_SECONDS}; применяется к следующей пачке сообщений.
          </span>
        </div>
      </div>

      <div className={uiStyles.card}>
        <h3>Авто-генерация черновиков</h3>
        <div className={styles.toggleRow}>
          <div className={styles.toggleLabel}>
            Для сообщений
            <span>черновик на каждую пачку после дебаунса</span>
          </div>
          <button
            type="button"
            className={uiStyles.switch}
            role="switch"
            aria-checked={value.autoGenerateDm}
            aria-label="Авто-генерация для сообщений"
            onClick={() => update("autoGenerateDm", !value.autoGenerateDm)}
            disabled={isPending}
          />
        </div>
        <p className={styles.fieldHint}>
          Черновики к комментариям не создаются автоматически — их запускает
          кнопка «Черновики» на экране «Комментарии».
        </p>
      </div>

      <div className={styles.aiFormFooter}>
        <div className={styles.aiFormState} aria-live="polite">
          {error ? (
            <p className={styles.formError} role="alert">
              {error}
            </p>
          ) : saved ? (
            <p className={styles.formSuccess} role="status">
              Настройки сохранены.
            </p>
          ) : isDirty ? (
            <p>Есть несохранённые изменения.</p>
          ) : null}
        </div>
        <button
          type="submit"
          className={`${uiStyles.button} ${uiStyles.buttonPrimary}`}
          disabled={isPending || !isDirty}
        >
          {isPending ? "Сохранение…" : "Сохранить"}
        </button>
      </div>
    </form>
  );
}
