"use client";

import { useMemo, useState, type FormEvent } from "react";

import type { AiModelOption } from "@/lib/ai/config";
import {
  DEFAULT_COMMENT_SYSTEM_PROMPT,
  DEFAULT_SYSTEM_PROMPT,
} from "@/lib/ai/default-prompts";
import {
  AI_DEBOUNCE_MAX_SECONDS,
  AI_DEBOUNCE_MIN_SECONDS,
  AI_SYSTEM_PROMPT_MAX_LENGTH,
  validateAiSettingsInput,
  type AiSettingsInput,
} from "@/lib/ai/settings";

import uiStyles from "../../_components/ui.module.css";
import styles from "../settings.module.css";
import { saveAiSettingsAction } from "./actions";
import { useActivityTransition } from "../../_components/activity";

export type AiSettingsFormValue = AiSettingsInput;

export function AiSettingsForm({
  initialValue,
  modelOptions,
}: {
  initialValue: AiSettingsFormValue;
  modelOptions: AiModelOption[];
}) {
  const [value, setValue] = useState(initialValue);
  const [savedValue, setSavedValue] = useState(initialValue);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [isPending, startTransition] = useActivityTransition("Сохраняем настройки…");
  const visibleModelOptions = useMemo(
    () =>
      value.model && !modelOptions.some((option) => option.value === value.model)
        ? [
            {
              value: value.model,
              label: `${value.model} (недоступна в текущем конфиге)`,
            },
            ...modelOptions,
          ]
        : modelOptions,
    [modelOptions, value.model],
  );
  const isDirty = JSON.stringify(value) !== JSON.stringify(savedValue);

  function update<K extends keyof AiSettingsFormValue>(
    key: K,
    next: AiSettingsFormValue[K],
  ) {
    setValue((current) => ({ ...current, [key]: next }));
    setError(null);
    setSaved(false);
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const validation = validateAiSettingsInput(
      value,
      modelOptions.map((option) => option.value),
    );

    if (!validation.ok) {
      setSaved(false);
      setError(validation.error);
      return;
    }

    setError(null);
    setSaved(false);
    startTransition(async () => {
      const result = await saveAiSettingsAction(validation.data);

      if (!result.ok) {
        setError(result.error);
        return;
      }

      const persisted: AiSettingsFormValue = {
        systemPrompt: result.data.system_prompt,
        commentSystemPrompt: result.data.comment_system_prompt,
        debounceSeconds: result.data.debounce_seconds,
        model: result.data.model,
        autoGenerateDm: result.data.auto_generate_dm,
      };
      setValue(persisted);
      setSavedValue(persisted);
      setSaved(true);
    });
  }

  return (
    <form className={styles.aiForm} onSubmit={handleSubmit}>
      <div className={`${uiStyles.card} ${uiStyles.cardStack}`}>
        <h3>Системные промпты</h3>
        <p className={styles.fieldHint}>
          Тон, язык ответов и подпись задаются прямо в тексте промпта. После
          промпта модель получает «действие» присвоенной категории, а затем сам
          вопрос клиента.
        </p>
        <div className={uiStyles.field}>
          <label htmlFor="ai-system-prompt">Черновики сообщений</label>
          <textarea
            id="ai-system-prompt"
            className={styles.aiPromptInput}
            value={value.systemPrompt}
            onChange={(event) => update("systemPrompt", event.target.value)}
            maxLength={AI_SYSTEM_PROMPT_MAX_LENGTH}
            rows={16}
            disabled={isPending}
          />
          <div className={styles.aiPromptFooter}>
            <span className={styles.fieldHint}>
              {value.systemPrompt.length} из {AI_SYSTEM_PROMPT_MAX_LENGTH}{" "}
              символов.
            </span>
            <button
              type="button"
              className={`${uiStyles.button} ${uiStyles.buttonGhost} ${uiStyles.buttonSmall}`}
              onClick={() => update("systemPrompt", DEFAULT_SYSTEM_PROMPT)}
              disabled={isPending || value.systemPrompt === DEFAULT_SYSTEM_PROMPT}
            >
              Вернуть шаблон
            </button>
          </div>
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-comment-system-prompt">Черновики комментариев</label>
          <textarea
            id="ai-comment-system-prompt"
            className={styles.aiPromptInput}
            value={value.commentSystemPrompt}
            onChange={(event) =>
              update("commentSystemPrompt", event.target.value)
            }
            maxLength={AI_SYSTEM_PROMPT_MAX_LENGTH}
            rows={16}
            disabled={isPending}
          />
          <div className={styles.aiPromptFooter}>
            <span className={styles.fieldHint}>
              {value.commentSystemPrompt.length} из{" "}
              {AI_SYSTEM_PROMPT_MAX_LENGTH} символов.
            </span>
            <button
              type="button"
              className={`${uiStyles.button} ${uiStyles.buttonGhost} ${uiStyles.buttonSmall}`}
              onClick={() =>
                update("commentSystemPrompt", DEFAULT_COMMENT_SYSTEM_PROMPT)
              }
              disabled={
                isPending ||
                value.commentSystemPrompt === DEFAULT_COMMENT_SYSTEM_PROMPT
              }
            >
              Вернуть шаблон
            </button>
          </div>
        </div>
      </div>

      <div className={`${uiStyles.card} ${uiStyles.cardStack}`}>
        <div className={uiStyles.field}>
          <label htmlFor="ai-model">Модель</label>
          <select
            id="ai-model"
            value={value.model}
            onChange={(event) => update("model", event.target.value)}
            disabled={isPending}
          >
            <option value="">Авто — модель из конфигурации</option>
            {visibleModelOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>
        <div className={uiStyles.field}>
          <label htmlFor="ai-debounce">Пауза перед генерацией</label>
          <div className={styles.aiDebounceField}>
            <input
              id="ai-debounce"
              type="number"
              min={AI_DEBOUNCE_MIN_SECONDS}
              max={AI_DEBOUNCE_MAX_SECONDS}
              step={1}
              value={value.debounceSeconds}
              onChange={(event) =>
                update("debounceSeconds", event.target.valueAsNumber)
              }
              disabled={isPending}
            />
            <span>секунд</span>
          </div>
          <span className={styles.fieldHint}>
            Целое число от {AI_DEBOUNCE_MIN_SECONDS} до{" "}
            {AI_DEBOUNCE_MAX_SECONDS}; применяется к следующей пачке сообщений.
          </span>
        </div>
      </div>

      <div className={uiStyles.card}>
        <h3>Авто-генерация черновиков</h3>
        <div className={styles.toggleRow}>
          <div className={styles.toggleLabel}>
            Для сообщений
            <span>черновик на каждую пачку после дебаунса</span>
          </div>
          <button
            type="button"
            className={uiStyles.switch}
            role="switch"
            aria-checked={value.autoGenerateDm}
            aria-label="Авто-генерация для сообщений"
            onClick={() => update("autoGenerateDm", !value.autoGenerateDm)}
            disabled={isPending}
          />
        </div>
        <p className={styles.fieldHint}>
          Черновики к комментариям не создаются автоматически — их запускает
          кнопка «Черновики» на экране «Комментарии».
        </p>
      </div>

      <div className={styles.aiFormFooter}>
        <div className={styles.aiFormState} aria-live="polite">
          {error ? (
            <p className={styles.formError} role="alert">
              {error}
            </p>
          ) : saved ? (
            <p className={styles.formSuccess} role="status">
              Настройки сохранены.
            </p>
          ) : isDirty ? (
            <p>Есть несохранённые изменения.</p>
          ) : null}
        </div>
        <button
          type="submit"
          className={`${uiStyles.button} ${uiStyles.buttonPrimary}`}
          disabled={isPending || !isDirty}
        >
          {isPending ? "Сохранение…" : "Сохранить"}
        </button>
      </div>
    </form>
  );
}
