// @vitest-environment jsdom

import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { AiSettingsForm, type AiSettingsFormValue } from "./ai-settings-form";

const saveAiSettingsAction = vi.fn();

vi.mock("./actions", () => ({
  saveAiSettingsAction: (...args: unknown[]) => saveAiSettingsAction(...args),
}));

const initialValue: AiSettingsFormValue = {
  tone: "friendly",
  language: "de",
  signature: "Viele Grüße",
  debounceSeconds: 45,
  model: "mistral-large-latest",
  autoGenerateDm: true,
};

const modelOptions = [
  { value: "mistral-small-latest", label: "Mistral Small (EU)" },
  { value: "mistral-large-latest", label: "Mistral Large (EU)" },
];

beforeEach(() => {
  saveAiSettingsAction.mockResolvedValue({
    ok: true,
    data: {
      tone: "friendly",
      language: "de",
      signature: "Viele Grüße",
      debounce_seconds: 60,
      model: "",
      auto_generate_dm: true,
    },
  });
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("AiSettingsForm", () => {
  it("renders current workspace values and every editable setting", () => {
    render(
      <AiSettingsForm initialValue={initialValue} modelOptions={modelOptions} />,
    );

    expect((screen.getByLabelText("Тон ответов") as HTMLSelectElement).value).toBe(
      "friendly",
    );
    expect((screen.getByLabelText("Язык ответов") as HTMLSelectElement).value).toBe(
      "de",
    );
    expect((screen.getByLabelText("Подпись") as HTMLInputElement).value).toBe(
      "Viele Grüße",
    );
    expect(
      (screen.getByLabelText("Пауза перед генерацией") as HTMLInputElement).value,
    ).toBe("45");
    expect((screen.getByLabelText("Модель") as HTMLSelectElement).value).toBe(
      "mistral-large-latest",
    );
    expect(
      screen
        .getByRole("switch", { name: "Авто-генерация для сообщений" })
        .getAttribute("aria-checked"),
    ).toBe("true");
    expect(
      screen.getByText(/Черновики к комментариям не создаются автоматически/),
    ).toBeDefined();
  });

  it("keeps optimistic edits, shows pending state and confirms persistence", async () => {
    render(
      <AiSettingsForm initialValue={initialValue} modelOptions={modelOptions} />,
    );

    fireEvent.change(screen.getByLabelText("Пауза перед генерацией"), {
      target: { value: "60" },
    });
    fireEvent.change(screen.getByLabelText("Модель"), {
      target: { value: "" },
    });
    expect(screen.getByText("Есть несохранённые изменения.")).toBeDefined();
    fireEvent.click(screen.getByRole("button", { name: "Сохранить" }));

    await waitFor(() =>
      expect(saveAiSettingsAction).toHaveBeenCalledWith({
        ...initialValue,
        debounceSeconds: 60,
        model: "",
      }),
    );
    expect((await screen.findByRole("status")).textContent).toContain(
      "Настройки сохранены.",
    );
  });

  it("shows validation and server errors without discarding edits", async () => {
    const unavailableValue = {
      ...initialValue,
      model: "removed-model",
    };
    render(
      <AiSettingsForm
        initialValue={unavailableValue}
        modelOptions={modelOptions}
      />,
    );

    fireEvent.change(screen.getByLabelText("Подпись"), {
      target: { value: "Edited locally" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Сохранить" }));
    expect(screen.getByRole("alert").textContent).toContain(
      "Выбранная модель недоступна.",
    );
    expect(saveAiSettingsAction).not.toHaveBeenCalled();

    cleanup();
    saveAiSettingsAction.mockClear();
    saveAiSettingsAction.mockResolvedValueOnce({
      ok: false,
      error: "Не удалось сохранить AI-настройки.",
    });
    render(
      <AiSettingsForm
        initialValue={initialValue}
        modelOptions={modelOptions}
      />,
    );
    fireEvent.change(screen.getByLabelText("Подпись"), {
      target: { value: "Edited locally" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Сохранить" }));

    expect((await screen.findByRole("alert")).textContent).toContain(
      "Не удалось сохранить AI-настройки.",
    );
    expect((screen.getByLabelText("Подпись") as HTMLInputElement).value).toBe(
      "Edited locally",
    );
  });
});
