import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const {
  runDraftPipeline,
  selectBatchMessages,
  selectCategoryForBatch,
} = await import("./draft-pipeline");
import type { CategoryRow } from "@/lib/db/categories";
import type {
  DraftPipelineDependencies,
  DraftPipelineSteps,
  LoadedDraftContext,
  PipelineMessage,
} from "./draft-pipeline";

class TestSteps implements DraftPipelineSteps {
  readonly runs: string[] = [];
  readonly sleeps: Array<{ id: string; duration: string }> = [];

  async run<T>(id: string, handler: () => Promise<T> | T): Promise<T> {
    this.runs.push(id);
    return handler();
  }

  async sleep(id: string, duration: string): Promise<void> {
    this.sleeps.push({ id, duration });
  }
}

function message(
  id: string,
  direction: "incoming" | "outgoing",
  text: string,
  categoryId: string | null = null,
): PipelineMessage {
  return {
    id,
    direction,
    text,
    categoryId,
    createdAt: `2026-07-22T10:00:0${id.at(-1) ?? "0"}.000Z`,
  };
}

function context(
  overrides: Partial<LoadedDraftContext> = {},
): LoadedDraftContext {
  const messages = [
    message("m0", "outgoing", "How can we help?"),
    message("m1", "incoming", "Please call +49 151 23456789", "category-1"),
  ];

  return {
    workspaceId: "workspace-1",
    conversationId: "conversation-1",
    conversationKind: "dm",
    aiSettings: {
      tone: "professional",
      language: "de",
      signature: "Support",
      debounceSeconds: 45,
      model: "mistral-large-latest",
      autoGenerateDm: true,
      autoGenerateComments: true,
    },
    messages,
    batchMessages: [messages[1]!],
    postText: "",
    contactNotes: "",
    channelCapabilities: {
      responseWindowHours: null,
      supportsAttachments: true,
      supportsReadReceipts: true,
      maxMessageLength: 4096,
      threadingStyle: "flat",
      supportsComments: false,
    },
    knowledgeBase: {
      text: "Hotline: +49 151 23456789. Product Alpha costs 10 EUR.",
      usedFileIds: ["kb-1"],
      omittedFileIds: ["kb-2"],
      enabledFileCount: 2,
      enabledTokenCount: 100,
      tokenBudget: 24_000,
      exceedsBudget: false,
      usedTokenCount: 70,
    },
    selectedCategory: {
      id: "category-1",
      name: "Pricing",
      description: "Questions about price",
      draftInstruction: "Mention the current price.",
      skipDraft: false,
    },
    ...overrides,
  };
}

function dependencies(
  overrides: Partial<DraftPipelineDependencies> = {},
): DraftPipelineDependencies {
  return {
    loadDebounceContext: vi
      .fn()
      .mockResolvedValue({ kind: "dm", debounceSeconds: 45 }),
    isLatestIncoming: vi.fn().mockResolvedValue(true),
    loadContext: vi.fn().mockResolvedValue(context()),
    createGeneratingDraft: vi.fn().mockResolvedValue("draft-1"),
    resolveModel: vi.fn((requestedModel: string) => requestedModel),
    generate: vi.fn().mockResolvedValue("We will call {{PHONE_1}}."),
    finalizeDraft: vi.fn().mockResolvedValue(undefined),
    cleanupGeneratingDrafts: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  };
}

describe("draft pipeline", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("runs masked KB/category/context through lib/ai and restores the completion", async () => {
    const steps = new TestSteps();
    let llmPrompt = "";
    const createGeneratingDraft = vi.fn().mockImplementation(({ context }) => {
      expect(context.knowledgeBase.usedFileIds).toEqual(["kb-1"]);
      return "draft-1";
    });
    const generate = vi.fn().mockImplementation((prompt) => {
      llmPrompt = JSON.stringify(prompt);
      return "We will call {{PHONE_1}}.";
    });
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({ createGeneratingDraft, generate, finalizeDraft }),
    );

    expect(result).toEqual({ status: "ready", draftId: "draft-1" });
    expect(steps.sleeps).toEqual([
      { id: "workspace-debounce", duration: "45s" },
    ]);
    expect(steps.runs).toEqual([
      "load-debounce-settings",
      "last-event-check",
      "load-context",
      "stop-check",
      "mask",
      "create-generating",
      "generate",
      "restore",
      "finalize",
    ]);
    expect(llmPrompt).not.toContain("+49 151 23456789");
    expect(llmPrompt).toContain("{{PHONE_1}}");
    expect(llmPrompt).toContain("Product Alpha costs 10 EUR");
    expect(llmPrompt).toContain("Mention the current price");
    expect(finalizeDraft).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      draftId: "draft-1",
      text: "We will call +49 151 23456789.",
      model: "mistral-large-latest",
      supersedeEdited: false,
      commentScoped: false,
    });
  });

  it("uses and persists the provider-resolved model instead of ai_settings.model", async () => {
    const generate = vi.fn().mockResolvedValue("Generated response");
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        resolveModel: vi.fn().mockReturnValue("mistralai/mistral-small-2603"),
        generate,
        finalizeDraft,
      }),
    );

    expect(generate).toHaveBeenCalledWith(
      expect.any(Array),
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
  });

  it("lets only the last of three debounced events create a draft", async () => {
    const createGeneratingDraft = vi.fn().mockResolvedValue("draft-1");
    const base = dependencies({
      isLatestIncoming: vi
        .fn()
        .mockImplementation(({ messageId }) => messageId === "m3"),
      loadContext: vi.fn().mockImplementation(({ messageId }) =>
        messageId === "m3" ? context() : null,
      ),
      createGeneratingDraft,
    });

    for (const messageId of ["m1", "m2", "m3"]) {
      await runDraftPipeline(
        {
          workspaceId: "workspace-1",
          conversationId: "conversation-1",
          messageId,
          regenerate: false,
        },
        new TestSteps(),
        base,
      );
    }

    expect(base.loadDebounceContext).toHaveBeenCalledTimes(3);
    expect(base.isLatestIncoming).toHaveBeenCalledTimes(3);
    expect(createGeneratingDraft).toHaveBeenCalledTimes(1);
  });

  it("stops before masking and draft creation when DM auto-generation is disabled", async () => {
    const createGeneratingDraft = vi.fn();
    const steps = new TestSteps();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "auto-generation-disabled",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
    expect(steps.runs).not.toContain("mask");
  });

  it("respects the existing category skip_draft flag", async () => {
    const createGeneratingDraft = vi.fn();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            selectedCategory: {
              ...context().selectedCategory,
              skipDraft: true,
            },
          }),
        ),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "category-skips-draft",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
  });

  it("regenerates immediately even with auto-generation disabled and supersedes edited", async () => {
    const steps = new TestSteps();
    const loadDebounceContext = vi.fn();
    const isLatestIncoming = vi.fn();
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        regenerate: true,
      },
      steps,
      dependencies({
        loadDebounceContext,
        isLatestIncoming,
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        finalizeDraft,
      }),
    );

    expect(result.status).toBe("ready");
    expect(loadDebounceContext).not.toHaveBeenCalled();
    expect(isLatestIncoming).not.toHaveBeenCalled();
    expect(steps.sleeps).toEqual([]);
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ supersedeEdited: true }),
    );
  });

  it("returns without a draft for an empty incoming batch", async () => {
    const createGeneratingDraft = vi.fn();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi.fn().mockResolvedValue(null),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({ status: "skipped", reason: "empty-batch" });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
  });

  it("generates a comment draft immediately without debounce and scopes finalize", async () => {
    const steps = new TestSteps();
    const comment = message("c1", "incoming", "Сколько стоит доставка?");
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "post-1",
        messageId: "c1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadDebounceContext: vi
          .fn()
          .mockResolvedValue({ kind: "comments", debounceSeconds: 45 }),
        loadContext: vi.fn().mockResolvedValue(
          context({
            conversationKind: "comments",
            messages: [comment],
            batchMessages: [comment],
            postText: "Осенняя коллекция уже в продаже!",
          }),
        ),
        finalizeDraft,
      }),
    );

    expect(result.status).toBe("ready");
    // No debounce for comments: no sleep, no last-event supersede check.
    expect(steps.sleeps).toEqual([]);
    expect(steps.runs).not.toContain("last-event-check");
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ commentScoped: true }),
    );
  });

  it("stops for a comment when comment auto-generation is disabled", async () => {
    const createGeneratingDraft = vi.fn();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "post-1",
        messageId: "c1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadDebounceContext: vi
          .fn()
          .mockResolvedValue({ kind: "comments", debounceSeconds: 45 }),
        loadContext: vi.fn().mockResolvedValue(
          context({
            conversationKind: "comments",
            aiSettings: { ...context().aiSettings, autoGenerateComments: false },
          }),
        ),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "auto-generation-disabled",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
  });
});

describe("selectBatchMessages", () => {
  it("uses only incoming messages after the latest outgoing message", () => {
    const messages = [
      message("m1", "incoming", "old"),
      message("m2", "outgoing", "answered"),
      message("m3", "incoming", "new one"),
      message("m4", "incoming", "new two"),
    ];

    expect(selectBatchMessages(messages).map(({ id }) => id)).toEqual([
      "m3",
      "m4",
    ]);
  });
});

describe("selectCategoryForBatch", () => {
  const categories: CategoryRow[] = [
    {
      id: "assigned",
      workspace_id: "workspace-1",
      name: "Assigned",
      description: "Assigned category",
      draft_instruction: "Use assigned action",
      channel_connection_ids: [],
      incoming_kind: "dm",
      skip_draft: false,
      priority: 0,
      is_default: false,
      created_at: "2026-07-22T00:00:00.000Z",
      updated_at: "2026-07-22T00:00:00.000Z",
    },
    {
      id: "default",
      workspace_id: "workspace-1",
      name: "Default",
      description: "Default category",
      draft_instruction: null,
      channel_connection_ids: [],
      incoming_kind: "both",
      skip_draft: false,
      priority: 1,
      is_default: true,
      created_at: "2026-07-22T00:00:00.000Z",
      updated_at: "2026-07-22T00:00:00.000Z",
    },
  ];

  it("uses an already assigned category on the triggering incoming message", () => {
    expect(
      selectCategoryForBatch(
        categories,
        [message("m1", "incoming", "one", null), message("m2", "incoming", "two", "assigned")],
        "m2",
      ).id,
    ).toBe("assigned");
  });

  it("uses the existing system default when the incoming is unassigned", () => {
    expect(
      selectCategoryForBatch(
        categories,
        [message("m1", "incoming", "one", null)],
        "m1",
      ).id,
    ).toBe("default");
  });

  it("fails safely when the workspace has no default category", () => {
    expect(() =>
      selectCategoryForBatch(
        categories.filter((category) => !category.is_default),
        [message("m1", "incoming", "one", null)],
        "m1",
      ),
    ).toThrow("default category is unavailable");
  });
});
