import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const {
  runDraftPipeline,
  selectApplicableCategories,
  selectBatchMessages,
  selectCategoryForBatch,
} = await import("./draft-pipeline");
import type { CategoryRow } from "@/lib/db/categories";
import type {
  DraftPipelineDependencies,
  DraftPipelineSteps,
  LoadedDraftContext,
  PipelineMessage,
  SelectedPipelineCategory,
} from "./draft-pipeline";

class TestSteps implements DraftPipelineSteps {
  readonly runs: string[] = [];
  readonly sleeps: Array<{ id: string; duration: string }> = [];
  readonly waits: Array<{ id: string; event: string; timeout: string }> = [];

  /** Событие «запустить сейчас», которое отдаст `waitForEvent`. */
  constructor(private readonly earlyEvent: unknown = null) {}

  async run<T>(id: string, handler: () => Promise<T> | T): Promise<T> {
    this.runs.push(id);
    return handler();
  }

  async sleep(id: string, duration: string): Promise<void> {
    this.sleeps.push({ id, duration });
  }

  async waitForEvent(
    id: string,
    options: { event: string; timeout: string; match?: string },
  ): Promise<unknown> {
    this.waits.push({ id, event: options.event, timeout: options.timeout });
    return this.earlyEvent;
  }
}

function message(
  id: string,
  direction: "incoming" | "outgoing",
  text: string,
  categoryId: string | null = null,
): PipelineMessage {
  return {
    id,
    direction,
    text,
    categoryId,
    createdAt: `2026-07-22T10:00:0${id.at(-1) ?? "0"}.000Z`,
  };
}

const pricingCategory: SelectedPipelineCategory = {
  id: "category-1",
  name: "Pricing",
  description: "Questions about price",
  draftInstruction: "Mention the current price.",
  skipDraft: false,
  kbFileIds: null,
};

const defaultCategory: SelectedPipelineCategory = {
  id: "category-default",
  name: "По умолчанию",
  description: "Всё, что не подошло под правила выше.",
  draftInstruction: null,
  skipDraft: false,
  kbFileIds: null,
};

function context(
  overrides: Partial<LoadedDraftContext> = {},
): LoadedDraftContext {
  const messages = [
    message("m0", "outgoing", "How can we help?"),
    message("m1", "incoming", "Please call +49 151 23456789", "category-1"),
  ];

  return {
    workspaceId: "workspace-1",
    conversationId: "conversation-1",
    aiSettings: {
      systemPrompt: "Пиши от лица бизнеса.",
      debounceSeconds: 45,
      model: "mistral-large-latest",
      autoGenerateDm: true,
    },
    messages,
    batchMessages: [messages[1]!],
    contactNotes: "",
    channelCapabilities: {
      responseWindowHours: null,
      supportsAttachments: true,
      supportsReadReceipts: true,
      maxMessageLength: 4096,
      threadingStyle: "flat",
      supportsComments: false,
    },
    knowledgeFiles: [
      {
        id: "kb-1",
        name: "01-price.md",
        content: "Hotline: +49 151 23456789. Product Alpha costs 10 EUR.",
        sort_order: 0,
        is_enabled: true,
      },
      {
        id: "kb-2",
        name: "02-disabled.md",
        content: "Internal notes.",
        sort_order: 1,
        is_enabled: false,
      },
    ],
    applicableCategories: [pricingCategory, defaultCategory],
    defaultCategory,
    assignedCategory: pricingCategory,
    ...overrides,
  };
}

function dependencies(
  overrides: Partial<DraftPipelineDependencies> = {},
): DraftPipelineDependencies {
  return {
    loadDebounceContext: vi.fn().mockResolvedValue({
      debounceSeconds: 45,
      debounceUntil: "2026-07-22T10:00:45.000Z",
    }),
    isLatestIncoming: vi.fn().mockResolvedValue(true),
    clearDebounceDeadline: vi.fn().mockResolvedValue(undefined),
    loadContext: vi.fn().mockResolvedValue(context()),
    classifyCategory: vi.fn().mockResolvedValue(1),
    persistCategory: vi.fn().mockResolvedValue(undefined),
    createGeneratingDraft: vi.fn().mockResolvedValue("draft-1"),
    resolveModel: vi.fn((requestedModel: string) => requestedModel),
    generate: vi.fn().mockResolvedValue("We will call {{PHONE_1}}."),
    finalizeDraft: vi.fn().mockResolvedValue(undefined),
    cleanupGeneratingDrafts: vi.fn().mockResolvedValue(undefined),
    notifyPushReady: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  };
}

describe("draft pipeline", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("runs masked KB/category/context through lib/ai and restores the completion", async () => {
    const steps = new TestSteps();
    let llmPrompt = "";
    const createGeneratingDraft = vi.fn().mockImplementation(({ context }) => {
      expect(context.knowledgeBase.usedFileIds).toEqual(["kb-1"]);
      return "draft-1";
    });
    const generate = vi.fn().mockImplementation((prompt) => {
      llmPrompt = JSON.stringify(prompt);
      return "We will call {{PHONE_1}}.";
    });
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);
    const notifyPushReady = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        createGeneratingDraft,
        generate,
        finalizeDraft,
        notifyPushReady,
      }),
    );

    expect(result).toEqual({ status: "ready", draftId: "draft-1" });
    // Дебаунс — прерываемое окно, а не sleep.
    expect(steps.sleeps).toEqual([]);
    expect(steps.waits).toEqual([
      {
        id: "debounce-window",
        event: "draft/run-now.requested",
        timeout: "45s",
      },
    ]);
    expect(steps.runs).toEqual([
      "load-debounce-settings",
      "clear-debounce-deadline",
      "last-event-check",
      "load-context",
      "classify",
      "persist-category",
      "stop-check",
      "mask",
      "create-generating",
      "generate",
      "restore",
      "parse-completion",
      "finalize",
      "notify-push-ready",
    ]);
    // Instant push (§11) fires for a new incoming with IDs only (rule 7).
    expect(notifyPushReady).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      conversationId: "conversation-1",
      messageId: "m1",
    });
    expect(llmPrompt).not.toContain("+49 151 23456789");
    expect(llmPrompt).toContain("{{PHONE_1}}");
    expect(llmPrompt).toContain("Product Alpha costs 10 EUR");
    expect(llmPrompt).toContain("Mention the current price");
    expect(finalizeDraft).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      draftId: "draft-1",
      text: "We will call +49 151 23456789.",
      model: "mistral-large-latest",
      supersedeEdited: false,
      manualReviewReason: null,
    });
  });

  it("uses and persists the provider-resolved model instead of ai_settings.model", async () => {
    const generate = vi.fn().mockResolvedValue("Generated response");
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        resolveModel: vi.fn().mockReturnValue("mistralai/mistral-small-2603"),
        generate,
        finalizeDraft,
      }),
    );

    expect(generate).toHaveBeenCalledWith(
      expect.any(Array),
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
  });

  it("lets only the last of three debounced events create a draft", async () => {
    const createGeneratingDraft = vi.fn().mockResolvedValue("draft-1");
    const base = dependencies({
      isLatestIncoming: vi
        .fn()
        .mockImplementation(({ messageId }) => messageId === "m3"),
      loadContext: vi.fn().mockImplementation(({ messageId }) =>
        messageId === "m3" ? context() : null,
      ),
      createGeneratingDraft,
    });

    for (const messageId of ["m1", "m2", "m3"]) {
      await runDraftPipeline(
        {
          workspaceId: "workspace-1",
          conversationId: "conversation-1",
          messageId,
          regenerate: false,
        },
        new TestSteps(),
        base,
      );
    }

    expect(base.loadDebounceContext).toHaveBeenCalledTimes(3);
    expect(base.isLatestIncoming).toHaveBeenCalledTimes(3);
    expect(createGeneratingDraft).toHaveBeenCalledTimes(1);
  });

  it("stops before masking and draft creation when DM auto-generation is disabled", async () => {
    const createGeneratingDraft = vi.fn();
    const steps = new TestSteps();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "auto-generation-disabled",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
    expect(steps.runs).not.toContain("mask");
  });

  it("respects the category skip_draft flag but keeps the classification", async () => {
    const createGeneratingDraft = vi.fn();
    const persistCategory = vi.fn().mockResolvedValue(undefined);
    const steps = new TestSteps();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            applicableCategories: [
              { ...pricingCategory, skipDraft: true },
              defaultCategory,
            ],
          }),
        ),
        persistCategory,
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "category-skips-draft",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
    // Классификация выполняется всегда (docs/architecture/09-categories.md).
    expect(steps.runs.indexOf("persist-category")).toBeLessThan(
      steps.runs.indexOf("stop-check"),
    );
    expect(persistCategory).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      conversationId: "conversation-1",
      messageIds: ["m1"],
      categoryId: "category-1",
    });
  });

  it("regenerates immediately even with auto-generation disabled and supersedes edited", async () => {
    const steps = new TestSteps();
    const loadDebounceContext = vi.fn();
    const isLatestIncoming = vi.fn();
    const classifyCategory = vi.fn();
    const persistCategory = vi.fn();
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        regenerate: true,
      },
      steps,
      dependencies({
        loadDebounceContext,
        isLatestIncoming,
        classifyCategory,
        persistCategory,
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        finalizeDraft,
      }),
    );

    expect(result.status).toBe("ready");
    expect(loadDebounceContext).not.toHaveBeenCalled();
    expect(isLatestIncoming).not.toHaveBeenCalled();
    expect(steps.waits).toEqual([]);
    // Нового входящего нет — переклассифицировать нечего.
    expect(classifyCategory).not.toHaveBeenCalled();
    expect(persistCategory).not.toHaveBeenCalled();
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ supersedeEdited: true }),
    );
  });

  it("returns without a draft for an empty incoming batch", async () => {
    const createGeneratingDraft = vi.fn();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi.fn().mockResolvedValue(null),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({ status: "skipped", reason: "empty-batch" });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
  });
});

describe("debounce window", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("clears only its own deadline, so a newer window keeps counting down", async () => {
    const clearDebounceDeadline = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({ clearDebounceDeadline }),
    );

    expect(clearDebounceDeadline).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      conversationId: "conversation-1",
      notAfter: "2026-07-22T10:00:45.000Z",
    });
  });

  it("generates without waiting out the timeout when «запустить сейчас» arrives", async () => {
    const steps = new TestSteps({ name: "draft/run-now.requested" });
    const createGeneratingDraft = vi.fn().mockResolvedValue("draft-1");

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({ createGeneratingDraft }),
    );

    expect(result).toEqual({ status: "ready", draftId: "draft-1" });
    expect(steps.waits).toHaveLength(1);
    expect(createGeneratingDraft).toHaveBeenCalledTimes(1);
  });

  it("skips the wait entirely when the workspace debounce is zero", async () => {
    const steps = new TestSteps();

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadDebounceContext: vi.fn().mockResolvedValue({
          debounceSeconds: 0,
          debounceUntil: "2026-07-22T10:00:00.000Z",
        }),
      }),
    );

    // "0s" — невалидный timeout для Inngest.
    expect(steps.waits).toEqual([]);
  });
});

describe("category classification", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("does not call the LLM when the default category is the only candidate", async () => {
    const classifyCategory = vi.fn();
    const persistCategory = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi
          .fn()
          .mockResolvedValue(
            context({ applicableCategories: [defaultCategory] }),
          ),
        classifyCategory,
        persistCategory,
      }),
    );

    expect(classifyCategory).not.toHaveBeenCalled();
    expect(persistCategory).toHaveBeenCalledWith(
      expect.objectContaining({ categoryId: "category-default" }),
    );
  });

  it("calls the LLM once per batch and stores the choice on every message", async () => {
    const classifyCategory = vi.fn().mockResolvedValue(1);
    const persistCategory = vi.fn().mockResolvedValue(undefined);
    const messages = [
      message("m0", "outgoing", "How can we help?"),
      message("m1", "incoming", "How much is Alpha?"),
      message("m2", "incoming", "And when does it ship?"),
    ];

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m2",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            messages,
            batchMessages: [messages[1]!, messages[2]!],
            assignedCategory: null,
          }),
        ),
        classifyCategory,
        persistCategory,
      }),
    );

    expect(classifyCategory).toHaveBeenCalledTimes(1);
    expect(classifyCategory.mock.calls[0]![0]!.maskedMessages).toHaveLength(2);
    expect(persistCategory).toHaveBeenCalledWith(
      expect.objectContaining({
        messageIds: ["m1", "m2"],
        categoryId: "category-1",
      }),
    );
  });

  it("falls back to the default category on an unusable answer", async () => {
    const persistCategory = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        classifyCategory: vi.fn().mockResolvedValue(null),
        persistCategory,
      }),
    );

    expect(persistCategory).toHaveBeenCalledWith(
      expect.objectContaining({ categoryId: "category-default" }),
    );
  });

  it("passes masked category rules to the classifier, never raw identifiers", async () => {
    const classifyCategory = vi.fn().mockResolvedValue(1);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({ classifyCategory }),
    );

    const payload = JSON.stringify(classifyCategory.mock.calls[0]![0]);
    expect(payload).not.toContain("+49 151 23456789");
    expect(payload).toContain("{{PHONE_1}}");
  });
});

describe("grounding refusal", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("stores the reason and an empty draft when the model declines to invent facts", async () => {
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        generate: vi
          .fn()
          .mockResolvedValue(
            "NEEDS_MANUAL_REVIEW: В базе знаний нет срока доставки.",
          ),
        finalizeDraft,
      }),
    );

    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({
        text: "",
        manualReviewReason: "В базе знаний нет срока доставки.",
      }),
    );
  });
});

describe("selectBatchMessages", () => {
  it("uses only incoming messages after the latest outgoing message", () => {
    const messages = [
      message("m1", "incoming", "old"),
      message("m2", "outgoing", "answered"),
      message("m3", "incoming", "new one"),
      message("m4", "incoming", "new two"),
    ];

    expect(selectBatchMessages(messages).map(({ id }) => id)).toEqual([
      "m3",
      "m4",
    ]);
  });
});

const categoryRow = (
  overrides: Partial<CategoryRow> & Pick<CategoryRow, "id">,
): CategoryRow => ({
  workspace_id: "workspace-1",
  name: overrides.id,
  description: `${overrides.id} rule`,
  draft_instruction: null,
  channel_connection_ids: [],
  skip_draft: false,
  kb_file_ids: null,
  priority: 0,
  is_default: false,
  created_at: "2026-07-22T00:00:00.000Z",
  updated_at: "2026-07-22T00:00:00.000Z",
  ...overrides,
});

describe("selectApplicableCategories", () => {
  const categories: CategoryRow[] = [
    categoryRow({ id: "other-channel", priority: 0, channel_connection_ids: ["ch-2"] }),
    categoryRow({ id: "this-channel", priority: 1, channel_connection_ids: ["ch-1"] }),
    categoryRow({ id: "all-channels", priority: 2 }),
    categoryRow({ id: "default", priority: 3, is_default: true }),
  ];

  it("keeps channel-applicable categories in priority order with the default last", () => {
    expect(
      selectApplicableCategories(categories, "ch-1").map(({ id }) => id),
    ).toEqual(["this-channel", "all-channels", "default"]);
  });

  it("always keeps the default even when it would sort earlier", () => {
    const defaultFirst = [
      categoryRow({ id: "default", priority: 0, is_default: true }),
      categoryRow({ id: "rule", priority: 1 }),
    ];

    expect(
      selectApplicableCategories(defaultFirst, "ch-1").map(({ id }) => id),
    ).toEqual(["rule", "default"]);
  });
});

describe("selectCategoryForBatch", () => {
  const categories: CategoryRow[] = [
    categoryRow({ id: "assigned", draft_instruction: "Use assigned action" }),
    categoryRow({ id: "default", priority: 1, is_default: true }),
  ];

  it("uses an already assigned category on the triggering incoming message", () => {
    expect(
      selectCategoryForBatch(
        categories,
        [
          message("m1", "incoming", "one", null),
          message("m2", "incoming", "two", "assigned"),
        ],
        "m2",
      )?.id,
    ).toBe("assigned");
  });

  it("returns null when the batch carries no category yet", () => {
    expect(
      selectCategoryForBatch(
        categories,
        [message("m1", "incoming", "one", null)],
        "m1",
      ),
    ).toBeNull();
  });

  it("fails loudly when the assigned category vanished from the workspace", () => {
    expect(() =>
      selectCategoryForBatch(
        categories.filter((category) => category.id !== "assigned"),
        [message("m1", "incoming", "one", "assigned")],
        "m1",
      ),
    ).toThrow("assigned message category is unavailable");
  });
});
