import "server-only";

import {
  AiProviderError,
  buildDraftPrompt,
  generateCompletionWithUsage,
  logPromptIfEnabled,
  maskMessages,
  parseDraftCompletion,
  resolveGenerationModel,
  unmaskText,
  type AiMessage,
  type MaskedEntity,
} from "@/lib/ai";
import {
  buildKnowledgeBaseContext,
  type KnowledgeBaseContext,
  type KnowledgeFileForPrompt,
} from "@/lib/ai/knowledge-base";
import {
  getDefaultChannelCapabilities,
  type ChannelCapabilities,
} from "@/lib/channels/capabilities";
import type { ChannelPlatform } from "@/lib/channels/types";
import { createAdminSupabaseClient } from "@/lib/db/admin";
import { recordAiRequest } from "@/lib/db/ai-request-log";
import { recordAiUsage } from "@/lib/db/ai-usage";
import {
  listKnowledgeFiles,
  type KnowledgeFileRow,
} from "@/lib/db/knowledge-base";
import { emitPushNotifyRequested } from "@/lib/inngest/events";

export const DRAFT_CONTEXT_MESSAGE_LIMIT = 20;
export const DEFAULT_DRAFT_MAX_TOKENS = 800;

export type DraftPipelineInput = {
  workspaceId: string;
  conversationId: string;
  /** Present only for interaction/received; regeneration intentionally has no message payload. */
  messageId?: string;
  regenerate: boolean;
};

export type DraftPipelineResult =
  | { status: "ready"; draftId: string }
  | {
      status: "skipped";
      reason:
        | "invalid-event"
        | "superseded-event"
        | "empty-batch"
        | "auto-generation-disabled";
    };

export type DraftPipelineSteps = {
  run<T>(id: string, handler: () => Promise<T> | T): Promise<T>;
  sleep(id: string, duration: string): Promise<void>;
  /** Resolves with the matching event, or `null` when the timeout elapses. */
  waitForEvent(
    id: string,
    options: { event: string; timeout: string; match?: string },
  ): Promise<unknown>;
};

type PromptLogger = {
  info(message: string): void;
};

export type PipelineAiSettings = {
  systemPrompt: string;
  debounceSeconds: number;
  model: string;
  autoGenerateDm: boolean;
};

export type PipelineMessage = {
  id: string;
  direction: "incoming" | "outgoing";
  text: string;
  createdAt: string;
};

export type LoadedDraftContext = {
  workspaceId: string;
  conversationId: string;
  aiSettings: PipelineAiSettings;
  messages: PipelineMessage[];
  batchMessages: PipelineMessage[];
  channelCapabilities: ChannelCapabilities;
  /**
   * Categories of the workspace knowledge base, raw. The prompt fragment keeps
   * the active ones; the full list also resolves the names the model returns
   * back to `kb_files` ids.
   */
  knowledgeFiles: KnowledgeFileForPrompt[];
  /** The contact's notes (docs/architecture/16-rollout-plan.md, этап 7). */
  contactNotes: string;
};

/** Everything the generation call needs, already masked. */
type MaskedDraftContext = {
  workspaceId: string;
  conversationId: string;
  aiSettings: PipelineAiSettings;
  messages: PipelineMessage[];
  batchMessages: PipelineMessage[];
  channelCapabilities: ChannelCapabilities;
  knowledgeBase: KnowledgeBaseContext;
  contactNotes: string;
  entities: MaskedEntity[];
};

/** Enough of the interaction to decide how long to debounce it. */
export type DebounceContext = {
  debounceSeconds: number;
  /**
   * ISO deadline written to `conversations.draft_debounce_until` so the thread
   * can render a countdown. Computed inside the step, therefore stable across
   * retries of that step.
   */
  debounceUntil: string;
};

export type DraftPipelineDependencies = {
  loadDebounceContext(input: {
    workspaceId: string;
    conversationId: string;
    messageId: string;
  }): Promise<DebounceContext | null>;
  isLatestIncoming(input: {
    workspaceId: string;
    conversationId: string;
    messageId: string;
  }): Promise<boolean>;
  /** Clears the countdown, but never a deadline newer than this run's own. */
  clearDebounceDeadline(input: {
    workspaceId: string;
    conversationId: string;
    notAfter: string;
  }): Promise<void>;
  loadContext(input: DraftPipelineInput): Promise<LoadedDraftContext | null>;
  createGeneratingDraft(input: { context: MaskedDraftContext }): Promise<string>;
  resolveModel(requestedModel: string): string;
  generate(
    prompt: readonly AiMessage[],
    options: {
      model: string;
      maxTokens: number;
      workspaceId: string;
      /** Ties the logged exchange to the draft it produced (`ai_request_log`). */
      draftId: string;
    },
  ): Promise<string>;
  finalizeDraft(input: {
    workspaceId: string;
    draftId: string;
    text: string;
    model: string;
    supersedeEdited: boolean;
    manualReviewReason: string | null;
    /** Categories the model named; also replaces the conversation's set. */
    matchedKbFileIds: readonly string[];
  }): Promise<void>;
  cleanupGeneratingDrafts(input: {
    workspaceId: string;
    conversationId: string;
    lastMessageId?: string;
  }): Promise<void>;
  /**
   * Fires the ID-only `push/notify.requested` event after a draft is ready
   * (docs/architecture/11-realtime-pwa.md#web-push). Fail-safe: never throws
   * back into the pipeline — a missed instant push is picked up by the digest.
   */
  notifyPushReady(input: {
    workspaceId: string;
    conversationId: string;
    messageId: string;
  }): Promise<void>;
};

type QueryError = { code?: string } | null;

function assertQuerySucceeded(error: QueryError, operation: string): void {
  if (!error) {
    return;
  }

  const code = error.code ? ` (${error.code})` : "";
  throw new Error(`${operation} failed${code}.`);
}

function normalizeDebounceSeconds(value: unknown): number {
  if (typeof value !== "number" || !Number.isInteger(value)) {
    throw new Error("Workspace debounce setting is invalid.");
  }

  // Mirrors the database constraint and keeps step.sleep deterministic even
  // if a damaged row bypassed it.
  if (value < 0 || value > 600) {
    throw new Error("Workspace debounce setting is outside the allowed range.");
  }

  return value;
}

function isChannelPlatform(value: unknown): value is ChannelPlatform {
  return (
    value === "telegram" ||
    value === "whatsapp" ||
    value === "instagram" ||
    value === "facebook"
  );
}

function channelCapabilities(
  platformValue: unknown,
  storedValue: unknown,
): ChannelCapabilities {
  if (!isChannelPlatform(platformValue)) {
    throw new Error("Conversation channel platform is unsupported.");
  }

  const defaults = getDefaultChannelCapabilities(platformValue);
  if (typeof storedValue !== "object" || storedValue === null) {
    return defaults;
  }

  const stored = storedValue as Partial<ChannelCapabilities>;
  return {
    responseWindowHours:
      stored.responseWindowHours === null ||
      typeof stored.responseWindowHours === "number"
        ? stored.responseWindowHours
        : defaults.responseWindowHours,
    supportsAttachments:
      typeof stored.supportsAttachments === "boolean"
        ? stored.supportsAttachments
        : defaults.supportsAttachments,
    supportsReadReceipts:
      typeof stored.supportsReadReceipts === "boolean"
        ? stored.supportsReadReceipts
        : defaults.supportsReadReceipts,
    maxMessageLength:
      stored.maxMessageLength === null ||
      typeof stored.maxMessageLength === "number"
        ? stored.maxMessageLength
        : defaults.maxMessageLength,
    threadingStyle:
      stored.threadingStyle === "flat" ||
      stored.threadingStyle === "parent" ||
      stored.threadingStyle === "email-headers"
        ? stored.threadingStyle
        : defaults.threadingStyle,
    supportsComments:
      typeof stored.supportsComments === "boolean"
        ? stored.supportsComments
        : defaults.supportsComments,
  };
}

function normalizeAiSettings(row: Record<string, unknown>): PipelineAiSettings {
  if (
    typeof row.system_prompt !== "string" ||
    typeof row.model !== "string" ||
    typeof row.auto_generate_dm !== "boolean"
  ) {
    throw new Error("Workspace AI settings are invalid.");
  }

  return {
    systemPrompt: row.system_prompt,
    debounceSeconds: normalizeDebounceSeconds(row.debounce_seconds),
    model: row.model,
    autoGenerateDm: row.auto_generate_dm,
  };
}

function normalizeMessage(row: Record<string, unknown>): PipelineMessage {
  if (
    typeof row.id !== "string" ||
    (row.direction !== "incoming" && row.direction !== "outgoing") ||
    typeof row.text !== "string" ||
    typeof row.created_at !== "string"
  ) {
    throw new Error("Conversation message data is invalid.");
  }

  return {
    id: row.id,
    direction: row.direction,
    text: row.text,
    createdAt: row.created_at,
  };
}

export function selectBatchMessages(
  chronologicalMessages: readonly PipelineMessage[],
): PipelineMessage[] {
  let lastOutgoingIndex = -1;
  chronologicalMessages.forEach((message, index) => {
    if (message.direction === "outgoing") {
      lastOutgoingIndex = index;
    }
  });

  return chronologicalMessages
    .slice(lastOutgoingIndex + 1)
    .filter((message) => message.direction === "incoming");
}

/**
 * Resolves the category names the model returned back to `kb_files` ids.
 *
 * The model never sees ids — it copies the names out of the knowledge-base
 * fragments — so this is the only place the two meet. Matching is
 * case-insensitive because a model that title-cases a name still means that
 * category, and names are unique per workspace under `lower(name)` anyway
 * (`kb_files_workspace_lower_name_idx`). A name that matches nothing is
 * dropped: an invented category is not a reason to fail a finished draft.
 */
export function resolveMatchedCategoryIds(
  files: readonly KnowledgeFileForPrompt[],
  categoryNames: readonly string[],
): string[] {
  const idByName = new Map(
    files.map((file) => [file.name.trim().toLocaleLowerCase("ru-RU"), file.id]),
  );

  const ids = categoryNames
    .map((name) => idByName.get(name.trim().toLocaleLowerCase("ru-RU")))
    .filter((id): id is string => Boolean(id));

  return [...new Set(ids)];
}

async function loadDebounceContext(input: {
  workspaceId: string;
  conversationId: string;
  messageId: string;
}): Promise<DebounceContext | null> {
  const supabase = createAdminSupabaseClient();
  const [{ data: conversation, error: conversationError }, { data: message, error: messageError }] =
    await Promise.all([
      supabase
        .from("conversations")
        .select("id")
        .eq("workspace_id", input.workspaceId)
        .eq("id", input.conversationId)
        .maybeSingle(),
      supabase
        .from("messages")
        .select("id")
        .eq("workspace_id", input.workspaceId)
        .eq("conversation_id", input.conversationId)
        .eq("id", input.messageId)
        .eq("direction", "incoming")
        .maybeSingle(),
    ]);

  assertQuerySucceeded(conversationError, "Loading debounce conversation");
  assertQuerySucceeded(messageError, "Loading debounce message");
  if (!conversation || !message) {
    return null;
  }

  const { data: settings, error: settingsError } = await supabase
    .from("ai_settings")
    .select("debounce_seconds")
    .eq("workspace_id", input.workspaceId)
    .maybeSingle();
  assertQuerySucceeded(settingsError, "Loading debounce settings");

  if (!settings) {
    throw new Error("Workspace AI settings are unavailable.");
  }

  const debounceSeconds = normalizeDebounceSeconds(settings.debounce_seconds);
  const debounceUntil = new Date(
    Date.now() + debounceSeconds * 1000,
  ).toISOString();

  // Publishing the deadline is what makes the countdown possible: the debounce
  // itself lives inside the Inngest run, which the browser cannot see.
  // `conversations` is already in the realtime publication, so the thread picks
  // this up without any extra plumbing. A later message overwrites it, which is
  // exactly right — the debounce restarts and so does the countdown.
  const { error: deadlineError } = await supabase
    .from("conversations")
    .update({ draft_debounce_until: debounceUntil })
    .eq("workspace_id", input.workspaceId)
    .eq("id", input.conversationId);
  assertQuerySucceeded(deadlineError, "Publishing the debounce deadline");

  return { debounceSeconds, debounceUntil };
}

/**
 * Hides the countdown once this run's window is over.
 *
 * `notAfter` is this run's own deadline: a superseded run waking up late must
 * not clear the deadline a newer message just published, which would freeze the
 * countdown of a window that is still running.
 */
async function clearDebounceDeadline(input: {
  workspaceId: string;
  conversationId: string;
  notAfter: string;
}): Promise<void> {
  const supabase = createAdminSupabaseClient();
  const { error } = await supabase
    .from("conversations")
    .update({ draft_debounce_until: null })
    .eq("workspace_id", input.workspaceId)
    .eq("id", input.conversationId)
    .lte("draft_debounce_until", input.notAfter);
  assertQuerySucceeded(error, "Clearing the debounce deadline");
}

async function isLatestIncoming(input: {
  workspaceId: string;
  conversationId: string;
  messageId: string;
}): Promise<boolean> {
  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase
    .from("messages")
    .select("id")
    .eq("workspace_id", input.workspaceId)
    .eq("conversation_id", input.conversationId)
    .eq("direction", "incoming")
    .order("created_at", { ascending: false })
    .order("id", { ascending: false })
    .limit(1)
    .maybeSingle();
  assertQuerySucceeded(error, "Checking the latest incoming message");

  return data?.id === input.messageId;
}

async function loadContext(
  input: DraftPipelineInput,
): Promise<LoadedDraftContext | null> {
  const supabase = createAdminSupabaseClient();
  const { data: conversation, error: conversationError } = await supabase
    .from("conversations")
    .select("id, workspace_id, channel_connection_id, contact_id")
    .eq("workspace_id", input.workspaceId)
    .eq("id", input.conversationId)
    .maybeSingle();
  assertQuerySucceeded(conversationError, "Loading draft conversation");

  if (!conversation) {
    return null;
  }

  const [
    { data: settings, error: settingsError },
    { data: connection, error: connectionError },
    { data: messageRows, error: messagesError },
    { data: contactRow, error: contactError },
    knowledgeFiles,
  ] = await Promise.all([
    supabase
      .from("ai_settings")
      .select("system_prompt, debounce_seconds, model, auto_generate_dm")
      .eq("workspace_id", input.workspaceId)
      .maybeSingle(),
    supabase
      .from("channel_connections")
      .select("id, platform, capabilities")
      .eq("workspace_id", input.workspaceId)
      .eq("id", conversation.channel_connection_id)
      .maybeSingle(),
    supabase
      .from("messages")
      .select("id, direction, text, created_at")
      .eq("workspace_id", input.workspaceId)
      .eq("conversation_id", input.conversationId)
      .order("created_at", { ascending: false })
      .order("id", { ascending: false })
      .limit(DRAFT_CONTEXT_MESSAGE_LIMIT),
    // Contact notes feed the prompt (docs/architecture/16-rollout-plan.md, этап 7).
    conversation.contact_id
      ? supabase
          .from("contacts")
          .select("notes")
          .eq("workspace_id", input.workspaceId)
          .eq("id", conversation.contact_id)
          .maybeSingle()
      : Promise.resolve({ data: null, error: null }),
    // Reuse the existing workspace-scoped knowledge base helper; there is no
    // parallel model or storage for the generation pipeline.
    listKnowledgeFiles(supabase, input.workspaceId),
  ]);

  assertQuerySucceeded(settingsError, "Loading AI settings");
  assertQuerySucceeded(connectionError, "Loading channel capabilities");
  assertQuerySucceeded(messagesError, "Loading conversation messages");
  assertQuerySucceeded(contactError, "Loading contact notes");

  if (!settings) {
    throw new Error("Workspace AI settings are unavailable.");
  }
  if (!connection) {
    throw new Error("Conversation channel connection is unavailable.");
  }

  const chronologicalMessages = ((messageRows ?? []) as Record<string, unknown>[])
    .map(normalizeMessage)
    .reverse();

  // A DM draft answers the whole un-replied batch after the debounce
  // (docs/architecture/07-data-flows.md#62-дебаунс-и-генерация-черновика).
  const messages = chronologicalMessages;
  const batchMessages = selectBatchMessages(messages);
  if (batchMessages.length === 0) {
    return null;
  }

  return {
    workspaceId: input.workspaceId,
    conversationId: input.conversationId,
    aiSettings: normalizeAiSettings(settings as Record<string, unknown>),
    messages,
    batchMessages,
    channelCapabilities: channelCapabilities(
      connection.platform,
      connection.capabilities,
    ),
    knowledgeFiles: knowledgeFiles satisfies KnowledgeFileRow[],
    contactNotes:
      contactRow && typeof contactRow.notes === "string" ? contactRow.notes : "",
  };
}

/**
 * Builds the knowledge base fragment and masks everything the generation call
 * will see, in one pass so the placeholder map returned here is the one that
 * unmasks the completion.
 */
export function buildGenerationContext(
  context: LoadedDraftContext,
): MaskedDraftContext {
  const knowledgeBase = buildKnowledgeBaseContext(context.knowledgeFiles);
  const values = [
    ...context.messages.map((message) => message.text),
    knowledgeBase.text,
    // Промпт маскируется вместе с остальным: пользователь мог вписать в него
    // телефон или email подписи, а `unmaskText` вернёт их в готовый черновик.
    context.aiSettings.systemPrompt,
    context.contactNotes,
  ];
  const { masked, entities } = maskMessages(values);
  let index = 0;
  const messages = context.messages.map((message) => ({
    ...message,
    text: masked[index++]!,
  }));
  const batchIds = new Set(context.batchMessages.map((message) => message.id));
  const batchMessages = messages.filter((message) => batchIds.has(message.id));
  const knowledgeBaseText = masked[index++]!;
  const systemPrompt = masked[index++]!;
  const contactNotes = masked[index++]!;

  return {
    workspaceId: context.workspaceId,
    conversationId: context.conversationId,
    messages,
    batchMessages,
    contactNotes,
    channelCapabilities: context.channelCapabilities,
    aiSettings: { ...context.aiSettings, systemPrompt },
    knowledgeBase: { ...knowledgeBase, text: knowledgeBaseText },
    entities,
  };
}

async function createGeneratingDraft(input: {
  context: MaskedDraftContext;
}): Promise<string> {
  const firstMessage = input.context.batchMessages[0];
  const lastMessage = input.context.batchMessages.at(-1);
  if (!firstMessage || !lastMessage) {
    throw new Error("Cannot create a draft for an empty message batch.");
  }

  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase
    .from("drafts")
    .insert({
      workspace_id: input.context.workspaceId,
      conversation_id: input.context.conversationId,
      first_message_id: firstMessage.id,
      last_message_id: lastMessage.id,
      status: "generating",
      kb_file_ids: input.context.knowledgeBase.usedFileIds,
    })
    .select("id")
    .single();
  assertQuerySucceeded(error, "Creating a generating draft");

  if (!data?.id) {
    throw new Error("Creating a generating draft returned no identifier.");
  }

  return data.id;
}

async function finalizeDraft(input: {
  workspaceId: string;
  draftId: string;
  text: string;
  model: string;
  supersedeEdited: boolean;
  manualReviewReason: string | null;
  matchedKbFileIds: readonly string[];
}): Promise<void> {
  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase.rpc("finalize_draft_generation", {
    target_workspace_id: input.workspaceId,
    target_draft_id: input.draftId,
    generated_text: input.text,
    generated_model: input.model,
    supersede_edited: input.supersedeEdited,
    review_reason: input.manualReviewReason,
    // Категории беседы всегда от последнего черновика: RPC перезаписывает набор
    // целиком под той же блокировкой, что и сам черновик.
    matched_kb_file_ids: [...input.matchedKbFileIds],
  });
  assertQuerySucceeded(error, "Finalizing a generated draft");

  if (data !== true) {
    throw new Error("The generating draft is no longer available to finalize.");
  }
}

export async function cleanupGeneratingDrafts(input: {
  workspaceId: string;
  conversationId: string;
  lastMessageId?: string;
}): Promise<void> {
  const supabase = createAdminSupabaseClient();
  let query = supabase
    .from("drafts")
    .delete()
    .eq("workspace_id", input.workspaceId)
    .eq("conversation_id", input.conversationId)
    .eq("status", "generating");

  if (input.lastMessageId) {
    query = query.eq("last_message_id", input.lastMessageId);
  }

  const { error } = await query;
  assertQuerySucceeded(error, "Cleaning up generating drafts");
}

export const draftPipelineDependencies: DraftPipelineDependencies = {
  loadDebounceContext,
  isLatestIncoming,
  clearDebounceDeadline,
  loadContext,
  createGeneratingDraft,
  resolveModel: resolveGenerationModel,
  generate: async (prompt, options) => {
    try {
      const completion = await generateCompletionWithUsage(prompt, {
        model: options.model,
        maxTokens: options.maxTokens,
        temperature: 0.3,
      });

      // Recorded inside the same Inngest step as the call itself: if the step is
      // retried the provider really was asked twice, so a second row is the
      // truthful accounting, not a duplicate.
      await recordAiUsage({
        workspaceId: options.workspaceId,
        operation: "draft",
        surface: "message",
        provider: completion.provider,
        model: completion.model,
        usage: completion.usage,
      });
      await recordAiRequest({
        workspaceId: options.workspaceId,
        operation: "draft",
        surface: "message",
        provider: completion.provider,
        model: completion.model,
        draftId: options.draftId,
        exchange: completion.exchange,
        usage: completion.usage,
      });

      return completion.text;
    } catch (error) {
      // A failed call is the one most worth reading back: the provider's error
      // body lives only in the exchange, since AiProviderError deliberately
      // drops the upstream message.
      if (error instanceof AiProviderError) {
        await recordAiRequest({
          workspaceId: options.workspaceId,
          operation: "draft",
          surface: "message",
          provider: error.provider,
          model: error.model ?? options.model,
          draftId: options.draftId,
          exchange: error.exchange ?? null,
          usage: null,
          errorCode: error.code,
        });
      }

      throw error;
    }
  },
  finalizeDraft,
  cleanupGeneratingDrafts,
  notifyPushReady: (input) => emitPushNotifyRequested(input),
};

export async function runDraftPipeline(
  input: DraftPipelineInput,
  steps: DraftPipelineSteps,
  dependencies: DraftPipelineDependencies = draftPipelineDependencies,
  logger?: PromptLogger,
): Promise<DraftPipelineResult> {
  if (!input.regenerate) {
    if (!input.messageId) {
      return { status: "skipped", reason: "invalid-event" };
    }

    const debounceContext = await steps.run("load-debounce-settings", () =>
      dependencies.loadDebounceContext({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        messageId: input.messageId!,
      }),
    );
    if (debounceContext === null) {
      return { status: "skipped", reason: "invalid-event" };
    }

    // Inngest v4's native debounce period is a static TimeStr, not a CEL
    // expression, so the workspace-specific delay is a durable wait followed by
    // a last-event check; only the newest event proceeds.
    //
    // The wait is `waitForEvent` rather than `sleep` because `sleep` cannot be
    // interrupted: «Запустить сейчас» sends `draft/run-now.requested`, which
    // ends the window early. The event wakes every waiting run of the
    // conversation, and the last-event check below drops all but the newest —
    // the same filtering that already handled the timeout path.
    if (debounceContext.debounceSeconds > 0) {
      await steps.waitForEvent("debounce-window", {
        event: "draft/run-now.requested",
        timeout: `${debounceContext.debounceSeconds}s`,
        match: "data.conversationId",
      });
    }

    await steps.run("clear-debounce-deadline", () =>
      dependencies.clearDebounceDeadline({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        notAfter: debounceContext.debounceUntil,
      }),
    );

    const isLatest = await steps.run("last-event-check", () =>
      dependencies.isLatestIncoming({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        messageId: input.messageId!,
      }),
    );
    if (!isLatest) {
      return { status: "skipped", reason: "superseded-event" };
    }
  }

  const context = await steps.run("load-context", () =>
    dependencies.loadContext(input),
  );
  if (!context) {
    return { status: "skipped", reason: "empty-batch" };
  }

  const stopReason = await steps.run("stop-check", () => {
    if (!input.regenerate && !context.aiSettings.autoGenerateDm) {
      return "auto-generation-disabled" as const;
    }
    return null;
  });
  if (stopReason) {
    return { status: "skipped", reason: stopReason };
  }

  const generationModel = dependencies.resolveModel(context.aiSettings.model);
  const maskedContext = await steps.run("mask", () =>
    buildGenerationContext(context),
  );
  const draftId = await steps.run("create-generating", () =>
    dependencies.createGeneratingDraft({ context: maskedContext }),
  );
  const completion = await steps.run("generate", async () => {
    const prompt = buildDraftPrompt({
      aiSettings: maskedContext.aiSettings,
      maskedMessages: maskedContext.messages.map((message) => ({
        direction: message.direction,
        text: message.text,
      })),
      channelCapabilities: maskedContext.channelCapabilities,
      knowledgeBase: maskedContext.knowledgeBase,
      maskedContactNotes: maskedContext.contactNotes || undefined,
    });
    logPromptIfEnabled(prompt, logger ? { logger } : undefined);

    return dependencies.generate(prompt, {
      model: generationModel,
      maxTokens: DEFAULT_DRAFT_MAX_TOKENS,
      workspaceId: input.workspaceId,
      draftId,
    });
  });
  // Unmask first, then parse: a refusal reason may itself mention a masked
  // value, and the marker check is unaffected by placeholder substitution.
  const restoredText = await steps.run("restore", () =>
    unmaskText(completion, maskedContext.entities),
  );
  const parsed = await steps.run("parse-completion", () =>
    parseDraftCompletion(restoredText),
  );
  // Имена категорий модель копирует из фрагментов базы знаний, поэтому
  // разворачиваем их в id по полному списку категорий workspace, а не только по
  // активным: выключенная после генерации категория всё ещё осмысленный ответ.
  const matchedKbFileIds = resolveMatchedCategoryIds(
    context.knowledgeFiles,
    parsed.categoryNames,
  );

  await steps.run("finalize", () =>
    dependencies.finalizeDraft({
      workspaceId: input.workspaceId,
      draftId,
      text: parsed.text,
      model: generationModel,
      supersedeEdited: input.regenerate,
      manualReviewReason: parsed.manualReviewReason,
      matchedKbFileIds,
    }),
  );

  // Instant push (docs/architecture/11-realtime-pwa.md#web-push): notify only
  // for a new incoming message (not regeneration, which answers no new arrival).
  // The event is IDs-only (rule 7); `send-push` builds the "черновик готов" copy
  // from names/channels server-side. Emitting inside a step memoizes it so a
  // retry of a later step never double-sends. Workspaces with auto-generation
  // off never reach here — those still surface in digests.
  if (!input.regenerate && input.messageId) {
    await steps.run("notify-push-ready", () =>
      dependencies.notifyPushReady({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        messageId: input.messageId!,
      }),
    );
  }

  return { status: "ready", draftId };
}
