import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

const { runDraftPipeline, resolveMatchedCategoryIds, selectBatchMessages } =
  await import("./draft-pipeline");
import type {
  DraftPipelineDependencies,
  DraftPipelineSteps,
  LoadedDraftContext,
  PipelineMessage,
} from "./draft-pipeline";

class TestSteps implements DraftPipelineSteps {
  readonly runs: string[] = [];
  readonly sleeps: Array<{ id: string; duration: string }> = [];
  readonly waits: Array<{ id: string; event: string; timeout: string }> = [];

  /** Событие «запустить сейчас», которое отдаст `waitForEvent`. */
  constructor(private readonly earlyEvent: unknown = null) {}

  async run<T>(id: string, handler: () => Promise<T> | T): Promise<T> {
    this.runs.push(id);
    return handler();
  }

  async sleep(id: string, duration: string): Promise<void> {
    this.sleeps.push({ id, duration });
  }

  async waitForEvent(
    id: string,
    options: { event: string; timeout: string; match?: string },
  ): Promise<unknown> {
    this.waits.push({ id, event: options.event, timeout: options.timeout });
    return this.earlyEvent;
  }
}

function message(
  id: string,
  direction: "incoming" | "outgoing",
  text: string,
): PipelineMessage {
  return {
    id,
    direction,
    text,
    createdAt: `2026-07-22T10:00:0${id.at(-1) ?? "0"}.000Z`,
  };
}

function context(
  overrides: Partial<LoadedDraftContext> = {},
): LoadedDraftContext {
  const messages = [
    message("m0", "outgoing", "How can we help?"),
    message("m1", "incoming", "Please call +49 151 23456789"),
  ];

  return {
    workspaceId: "workspace-1",
    conversationId: "conversation-1",
    aiSettings: {
      systemPrompt: "Пиши от лица бизнеса.",
      debounceSeconds: 45,
      model: "mistral-large-latest",
      autoGenerateDm: true,
    },
    messages,
    batchMessages: [messages[1]!],
    contactNotes: "",
    channelCapabilities: {
      responseWindowHours: null,
      supportsAttachments: true,
      supportsReadReceipts: true,
      maxMessageLength: 4096,
      threadingStyle: "flat",
      supportsComments: false,
    },
    knowledgeFiles: [
      {
        id: "kb-1",
        name: "Прайс",
        content: "Hotline: +49 151 23456789. Product Alpha costs 10 EUR.",
        sort_order: 0,
        is_enabled: true,
      },
      {
        id: "kb-2",
        name: "Внутреннее",
        content: "Internal notes.",
        sort_order: 1,
        is_enabled: false,
      },
    ],
    ...overrides,
  };
}

function dependencies(
  overrides: Partial<DraftPipelineDependencies> = {},
): DraftPipelineDependencies {
  return {
    loadDebounceContext: vi.fn().mockResolvedValue({
      debounceSeconds: 45,
      debounceUntil: "2026-07-22T10:00:45.000Z",
    }),
    isLatestIncoming: vi.fn().mockResolvedValue(true),
    clearDebounceDeadline: vi.fn().mockResolvedValue(undefined),
    loadContext: vi.fn().mockResolvedValue(context()),
    createGeneratingDraft: vi.fn().mockResolvedValue("draft-1"),
    resolveModel: vi.fn((requestedModel: string) => requestedModel),
    generate: vi
      .fn()
      .mockResolvedValue("CATEGORIES: Прайс\n\nWe will call {{PHONE_1}}."),
    finalizeDraft: vi.fn().mockResolvedValue(undefined),
    cleanupGeneratingDrafts: vi.fn().mockResolvedValue(undefined),
    notifyPushReady: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  };
}

describe("draft pipeline", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("runs the masked KB and context through lib/ai and restores the completion", async () => {
    const steps = new TestSteps();
    let llmPrompt = "";
    const createGeneratingDraft = vi.fn().mockImplementation(({ context }) => {
      expect(context.knowledgeBase.usedFileIds).toEqual(["kb-1"]);
      return "draft-1";
    });
    const generate = vi.fn().mockImplementation((prompt) => {
      llmPrompt = JSON.stringify(prompt);
      return "CATEGORIES: Прайс\n\nWe will call {{PHONE_1}}.";
    });
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);
    const notifyPushReady = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        createGeneratingDraft,
        generate,
        finalizeDraft,
        notifyPushReady,
      }),
    );

    expect(result).toEqual({ status: "ready", draftId: "draft-1" });
    // Дебаунс — прерываемое окно, а не sleep.
    expect(steps.sleeps).toEqual([]);
    expect(steps.waits).toEqual([
      {
        id: "debounce-window",
        event: "draft/run-now.requested",
        timeout: "45s",
      },
    ]);
    expect(steps.runs).toEqual([
      "load-debounce-settings",
      "clear-debounce-deadline",
      "last-event-check",
      "load-context",
      "stop-check",
      "mask",
      "create-generating",
      "generate",
      "restore",
      "parse-completion",
      "finalize",
      "notify-push-ready",
    ]);
    // Instant push (§11) fires for a new incoming with IDs only (rule 7).
    expect(notifyPushReady).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      conversationId: "conversation-1",
      messageId: "m1",
    });
    expect(llmPrompt).not.toContain("+49 151 23456789");
    expect(llmPrompt).toContain("{{PHONE_1}}");
    expect(llmPrompt).toContain("Product Alpha costs 10 EUR");
    // Категория названа моделью и развёрнута в id базы знаний.
    expect(finalizeDraft).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      draftId: "draft-1",
      text: "We will call +49 151 23456789.",
      model: "mistral-large-latest",
      supersedeEdited: false,
      manualReviewReason: null,
      matchedKbFileIds: ["kb-1"],
    });
  });

  it("uses and persists the provider-resolved model instead of ai_settings.model", async () => {
    const generate = vi.fn().mockResolvedValue("Generated response");
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        resolveModel: vi.fn().mockReturnValue("mistralai/mistral-small-2603"),
        generate,
        finalizeDraft,
      }),
    );

    expect(generate).toHaveBeenCalledWith(
      expect.any(Array),
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ model: "mistralai/mistral-small-2603" }),
    );
  });

  it("lets only the last of three debounced events create a draft", async () => {
    const createGeneratingDraft = vi.fn().mockResolvedValue("draft-1");
    const base = dependencies({
      isLatestIncoming: vi
        .fn()
        .mockImplementation(({ messageId }) => messageId === "m3"),
      loadContext: vi.fn().mockImplementation(({ messageId }) =>
        messageId === "m3" ? context() : null,
      ),
      createGeneratingDraft,
    });

    for (const messageId of ["m1", "m2", "m3"]) {
      await runDraftPipeline(
        {
          workspaceId: "workspace-1",
          conversationId: "conversation-1",
          messageId,
          regenerate: false,
        },
        new TestSteps(),
        base,
      );
    }

    expect(base.loadDebounceContext).toHaveBeenCalledTimes(3);
    expect(base.isLatestIncoming).toHaveBeenCalledTimes(3);
    expect(createGeneratingDraft).toHaveBeenCalledTimes(1);
  });

  it("stops before masking and draft creation when DM auto-generation is disabled", async () => {
    const createGeneratingDraft = vi.fn();
    const steps = new TestSteps();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({
      status: "skipped",
      reason: "auto-generation-disabled",
    });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
    expect(steps.runs).not.toContain("mask");
  });

  it("regenerates immediately even with auto-generation disabled and supersedes edited", async () => {
    const steps = new TestSteps();
    const loadDebounceContext = vi.fn();
    const isLatestIncoming = vi.fn();
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        regenerate: true,
      },
      steps,
      dependencies({
        loadDebounceContext,
        isLatestIncoming,
        loadContext: vi.fn().mockResolvedValue(
          context({
            aiSettings: {
              ...context().aiSettings,
              autoGenerateDm: false,
            },
          }),
        ),
        finalizeDraft,
      }),
    );

    expect(result.status).toBe("ready");
    expect(loadDebounceContext).not.toHaveBeenCalled();
    expect(isLatestIncoming).not.toHaveBeenCalled();
    expect(steps.waits).toEqual([]);
    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({ supersedeEdited: true }),
    );
  });

  it("returns without a draft for an empty incoming batch", async () => {
    const createGeneratingDraft = vi.fn();
    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        loadContext: vi.fn().mockResolvedValue(null),
        createGeneratingDraft,
      }),
    );

    expect(result).toEqual({ status: "skipped", reason: "empty-batch" });
    expect(createGeneratingDraft).not.toHaveBeenCalled();
  });
});

describe("debounce window", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("clears only its own deadline, so a newer window keeps counting down", async () => {
    const clearDebounceDeadline = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({ clearDebounceDeadline }),
    );

    expect(clearDebounceDeadline).toHaveBeenCalledWith({
      workspaceId: "workspace-1",
      conversationId: "conversation-1",
      notAfter: "2026-07-22T10:00:45.000Z",
    });
  });

  it("generates without waiting out the timeout when «запустить сейчас» arrives", async () => {
    const steps = new TestSteps({ name: "draft/run-now.requested" });
    const createGeneratingDraft = vi.fn().mockResolvedValue("draft-1");

    const result = await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({ createGeneratingDraft }),
    );

    expect(result).toEqual({ status: "ready", draftId: "draft-1" });
    expect(steps.waits).toHaveLength(1);
    expect(createGeneratingDraft).toHaveBeenCalledTimes(1);
  });

  it("skips the wait entirely when the workspace debounce is zero", async () => {
    const steps = new TestSteps();

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      steps,
      dependencies({
        loadDebounceContext: vi.fn().mockResolvedValue({
          debounceSeconds: 0,
          debounceUntil: "2026-07-22T10:00:00.000Z",
        }),
      }),
    );

    // "0s" — невалидный timeout для Inngest.
    expect(steps.waits).toEqual([]);
  });
});

describe("grounding refusal", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("stores the reason and an empty draft when the model declines to invent facts", async () => {
    const finalizeDraft = vi.fn().mockResolvedValue(undefined);

    await runDraftPipeline(
      {
        workspaceId: "workspace-1",
        conversationId: "conversation-1",
        messageId: "m1",
        regenerate: false,
      },
      new TestSteps(),
      dependencies({
        generate: vi
          .fn()
          .mockResolvedValue(
            "CATEGORIES:\n\nNEEDS_MANUAL_REVIEW: В базе знаний нет срока доставки.",
          ),
        finalizeDraft,
      }),
    );

    expect(finalizeDraft).toHaveBeenCalledWith(
      expect.objectContaining({
        text: "",
        manualReviewReason: "В базе знаний нет срока доставки.",
        matchedKbFileIds: [],
      }),
    );
  });
});

describe("selectBatchMessages", () => {
  it("uses only incoming messages after the latest outgoing message", () => {
    const messages = [
      message("m1", "incoming", "old"),
      message("m2", "outgoing", "answered"),
      message("m3", "incoming", "new one"),
      message("m4", "incoming", "new two"),
    ];

    expect(selectBatchMessages(messages).map(({ id }) => id)).toEqual([
      "m3",
      "m4",
    ]);
  });
});

describe("resolveMatchedCategoryIds", () => {
  const files = [
    {
      id: "kb-1",
      name: "Прайс",
      content: "",
      sort_order: 0,
      is_enabled: true,
    },
    {
      id: "kb-2",
      name: "Возврат",
      content: "",
      sort_order: 1,
      is_enabled: false,
    },
  ];

  it("matches names case- and space-insensitively, including a disabled category", () => {
    // Категорию могли выключить уже после генерации — ответ от этого не
    // перестаёт быть осмысленным.
    expect(resolveMatchedCategoryIds(files, [" прайс ", "ВОЗВРАТ"])).toEqual([
      "kb-1",
      "kb-2",
    ]);
  });

  it("drops an invented name instead of failing a finished draft", () => {
    expect(resolveMatchedCategoryIds(files, ["Прайс", "Выдуманная"])).toEqual([
      "kb-1",
    ]);
  });

  it("collapses duplicates", () => {
    expect(resolveMatchedCategoryIds(files, ["Прайс", "Прайс"])).toEqual([
      "kb-1",
    ]);
  });
});
