import "server-only";

import {
  buildDraftPrompt,
  generateCompletion,
  logPromptIfEnabled,
  maskMessages,
  resolveGenerationModel,
  unmaskText,
  type AiMessage,
  type MaskedEntity,
  type PromptCategory,
} from "@/lib/ai";
import {
  buildKnowledgeBaseContext,
  type KnowledgeBaseContext,
} from "@/lib/ai/knowledge-base";
import {
  getDefaultChannelCapabilities,
  type ChannelCapabilities,
} from "@/lib/channels/capabilities";
import type { ChannelPlatform } from "@/lib/channels/types";
import {
  listCategories,
  type CategoryRow,
} from "@/lib/db/categories";
import { createAdminSupabaseClient } from "@/lib/db/admin";
import {
  listKnowledgeFiles,
  type KnowledgeFileRow,
} from "@/lib/db/knowledge-base";

export const DRAFT_CONTEXT_MESSAGE_LIMIT = 20;
export const DEFAULT_DRAFT_MAX_TOKENS = 800;

export type DraftPipelineInput = {
  workspaceId: string;
  conversationId: string;
  /** Present only for interaction/received; regeneration intentionally has no message payload. */
  messageId?: string;
  regenerate: boolean;
};

export type DraftPipelineResult =
  | { status: "ready"; draftId: string }
  | {
      status: "skipped";
      reason:
        | "invalid-event"
        | "superseded-event"
        | "empty-batch"
        | "auto-generation-disabled"
        | "category-skips-draft";
    };

export type DraftPipelineSteps = {
  run<T>(id: string, handler: () => Promise<T> | T): Promise<T>;
  sleep(id: string, duration: string): Promise<void>;
};

type PromptLogger = {
  info(message: string): void;
};

export type PipelineAiSettings = {
  tone: string;
  language: string;
  signature: string;
  debounceSeconds: number;
  model: string;
  autoGenerateDm: boolean;
};

export type PipelineMessage = {
  id: string;
  direction: "incoming" | "outgoing";
  text: string;
  categoryId: string | null;
  createdAt: string;
};

export type SelectedPipelineCategory = PromptCategory & {
  skipDraft: boolean;
};

export type LoadedDraftContext = {
  workspaceId: string;
  conversationId: string;
  conversationKind: "dm";
  aiSettings: PipelineAiSettings;
  messages: PipelineMessage[];
  batchMessages: PipelineMessage[];
  channelCapabilities: ChannelCapabilities;
  knowledgeBase: KnowledgeBaseContext;
  selectedCategory: SelectedPipelineCategory;
};

type MaskedDraftContext = Omit<
  LoadedDraftContext,
  "aiSettings" | "messages" | "batchMessages" | "knowledgeBase" | "selectedCategory"
> & {
  aiSettings: PipelineAiSettings;
  messages: PipelineMessage[];
  batchMessages: PipelineMessage[];
  knowledgeBase: KnowledgeBaseContext;
  selectedCategory: SelectedPipelineCategory;
  entities: MaskedEntity[];
};

export type DraftPipelineDependencies = {
  loadDebounceSeconds(input: {
    workspaceId: string;
    conversationId: string;
    messageId: string;
  }): Promise<number | null>;
  isLatestIncoming(input: {
    workspaceId: string;
    conversationId: string;
    messageId: string;
  }): Promise<boolean>;
  loadContext(input: DraftPipelineInput): Promise<LoadedDraftContext | null>;
  createGeneratingDraft(input: {
    context: LoadedDraftContext;
  }): Promise<string>;
  resolveModel(requestedModel: string): string;
  generate(
    prompt: readonly AiMessage[],
    options: { model: string; maxTokens: number },
  ): Promise<string>;
  finalizeDraft(input: {
    workspaceId: string;
    draftId: string;
    text: string;
    model: string;
    supersedeEdited: boolean;
  }): Promise<void>;
  cleanupGeneratingDrafts(input: {
    workspaceId: string;
    conversationId: string;
    lastMessageId?: string;
  }): Promise<void>;
};

type QueryError = { code?: string } | null;

function assertQuerySucceeded(error: QueryError, operation: string): void {
  if (!error) {
    return;
  }

  const code = error.code ? ` (${error.code})` : "";
  throw new Error(`${operation} failed${code}.`);
}

function normalizeDebounceSeconds(value: unknown): number {
  if (typeof value !== "number" || !Number.isInteger(value)) {
    throw new Error("Workspace debounce setting is invalid.");
  }

  // Mirrors the database constraint and keeps step.sleep deterministic even
  // if a damaged row bypassed it.
  if (value < 0 || value > 600) {
    throw new Error("Workspace debounce setting is outside the allowed range.");
  }

  return value;
}

function isChannelPlatform(value: unknown): value is ChannelPlatform {
  return (
    value === "telegram" ||
    value === "whatsapp" ||
    value === "instagram" ||
    value === "facebook"
  );
}

function channelCapabilities(
  platformValue: unknown,
  storedValue: unknown,
): ChannelCapabilities {
  if (!isChannelPlatform(platformValue)) {
    throw new Error("Conversation channel platform is unsupported.");
  }

  const defaults = getDefaultChannelCapabilities(platformValue);
  if (typeof storedValue !== "object" || storedValue === null) {
    return defaults;
  }

  const stored = storedValue as Partial<ChannelCapabilities>;
  return {
    responseWindowHours:
      stored.responseWindowHours === null ||
      typeof stored.responseWindowHours === "number"
        ? stored.responseWindowHours
        : defaults.responseWindowHours,
    supportsAttachments:
      typeof stored.supportsAttachments === "boolean"
        ? stored.supportsAttachments
        : defaults.supportsAttachments,
    supportsReadReceipts:
      typeof stored.supportsReadReceipts === "boolean"
        ? stored.supportsReadReceipts
        : defaults.supportsReadReceipts,
    maxMessageLength:
      stored.maxMessageLength === null ||
      typeof stored.maxMessageLength === "number"
        ? stored.maxMessageLength
        : defaults.maxMessageLength,
    threadingStyle:
      stored.threadingStyle === "flat" ||
      stored.threadingStyle === "parent" ||
      stored.threadingStyle === "email-headers"
        ? stored.threadingStyle
        : defaults.threadingStyle,
    supportsComments:
      typeof stored.supportsComments === "boolean"
        ? stored.supportsComments
        : defaults.supportsComments,
  };
}

function normalizeAiSettings(row: Record<string, unknown>): PipelineAiSettings {
  if (
    typeof row.tone !== "string" ||
    typeof row.language !== "string" ||
    typeof row.signature !== "string" ||
    typeof row.model !== "string" ||
    typeof row.auto_generate_dm !== "boolean"
  ) {
    throw new Error("Workspace AI settings are invalid.");
  }

  return {
    tone: row.tone,
    language: row.language,
    signature: row.signature,
    debounceSeconds: normalizeDebounceSeconds(row.debounce_seconds),
    model: row.model,
    autoGenerateDm: row.auto_generate_dm,
  };
}

function normalizeMessage(row: Record<string, unknown>): PipelineMessage {
  if (
    typeof row.id !== "string" ||
    (row.direction !== "incoming" && row.direction !== "outgoing") ||
    typeof row.text !== "string" ||
    typeof row.created_at !== "string" ||
    (row.category_id !== null && typeof row.category_id !== "string")
  ) {
    throw new Error("Conversation message data is invalid.");
  }

  return {
    id: row.id,
    direction: row.direction,
    text: row.text,
    categoryId: row.category_id,
    createdAt: row.created_at,
  };
}

export function selectBatchMessages(
  chronologicalMessages: readonly PipelineMessage[],
): PipelineMessage[] {
  let lastOutgoingIndex = -1;
  chronologicalMessages.forEach((message, index) => {
    if (message.direction === "outgoing") {
      lastOutgoingIndex = index;
    }
  });

  return chronologicalMessages
    .slice(lastOutgoingIndex + 1)
    .filter((message) => message.direction === "incoming");
}

export function selectCategoryForBatch(
  categories: readonly CategoryRow[],
  batchMessages: readonly PipelineMessage[],
  preferredMessageId?: string,
): SelectedPipelineCategory {
  const preferredMessage = preferredMessageId
    ? batchMessages.find((message) => message.id === preferredMessageId)
    : undefined;
  const categoryId = (preferredMessage ?? batchMessages.at(-1))?.categoryId;
  const category = categoryId
    ? categories.find((candidate) => candidate.id === categoryId)
    : categories.find((candidate) => candidate.is_default);

  if (!category) {
    throw new Error(
      categoryId
        ? "The assigned message category is unavailable in this workspace."
        : "The workspace default category is unavailable.",
    );
  }

  return {
    id: category.id,
    name: category.name,
    description: category.description,
    draftInstruction: category.draft_instruction,
    skipDraft: category.skip_draft,
  };
}

async function loadDebounceSeconds(input: {
  workspaceId: string;
  conversationId: string;
  messageId: string;
}): Promise<number | null> {
  const supabase = createAdminSupabaseClient();
  const [{ data: conversation, error: conversationError }, { data: message, error: messageError }] =
    await Promise.all([
      supabase
        .from("conversations")
        .select("id")
        .eq("workspace_id", input.workspaceId)
        .eq("id", input.conversationId)
        .eq("kind", "dm")
        .maybeSingle(),
      supabase
        .from("messages")
        .select("id")
        .eq("workspace_id", input.workspaceId)
        .eq("conversation_id", input.conversationId)
        .eq("id", input.messageId)
        .eq("direction", "incoming")
        .maybeSingle(),
    ]);

  assertQuerySucceeded(conversationError, "Loading debounce conversation");
  assertQuerySucceeded(messageError, "Loading debounce message");
  if (!conversation || !message) {
    return null;
  }

  const { data: settings, error: settingsError } = await supabase
    .from("ai_settings")
    .select("debounce_seconds")
    .eq("workspace_id", input.workspaceId)
    .maybeSingle();
  assertQuerySucceeded(settingsError, "Loading debounce settings");

  if (!settings) {
    throw new Error("Workspace AI settings are unavailable.");
  }

  return normalizeDebounceSeconds(settings.debounce_seconds);
}

async function isLatestIncoming(input: {
  workspaceId: string;
  conversationId: string;
  messageId: string;
}): Promise<boolean> {
  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase
    .from("messages")
    .select("id")
    .eq("workspace_id", input.workspaceId)
    .eq("conversation_id", input.conversationId)
    .eq("direction", "incoming")
    .order("created_at", { ascending: false })
    .order("id", { ascending: false })
    .limit(1)
    .maybeSingle();
  assertQuerySucceeded(error, "Checking the latest incoming message");

  return data?.id === input.messageId;
}

async function loadContext(
  input: DraftPipelineInput,
): Promise<LoadedDraftContext | null> {
  const supabase = createAdminSupabaseClient();
  const { data: conversation, error: conversationError } = await supabase
    .from("conversations")
    .select("id, workspace_id, kind, channel_connection_id")
    .eq("workspace_id", input.workspaceId)
    .eq("id", input.conversationId)
    .eq("kind", "dm")
    .maybeSingle();
  assertQuerySucceeded(conversationError, "Loading draft conversation");

  if (!conversation) {
    return null;
  }

  const [
    { data: settings, error: settingsError },
    { data: connection, error: connectionError },
    { data: messageRows, error: messagesError },
    knowledgeFiles,
    categories,
  ] = await Promise.all([
    supabase
      .from("ai_settings")
      .select(
        "tone, language, signature, debounce_seconds, model, auto_generate_dm",
      )
      .eq("workspace_id", input.workspaceId)
      .maybeSingle(),
    supabase
      .from("channel_connections")
      .select("id, platform, capabilities")
      .eq("workspace_id", input.workspaceId)
      .eq("id", conversation.channel_connection_id)
      .maybeSingle(),
    supabase
      .from("messages")
      .select("id, direction, text, category_id, created_at")
      .eq("workspace_id", input.workspaceId)
      .eq("conversation_id", input.conversationId)
      .order("created_at", { ascending: false })
      .order("id", { ascending: false })
      .limit(DRAFT_CONTEXT_MESSAGE_LIMIT),
    // Reuse the existing workspace-scoped KB and category server helpers;
    // there is no parallel model or storage for the generation pipeline.
    listKnowledgeFiles(supabase, input.workspaceId),
    listCategories(supabase, input.workspaceId),
  ]);

  assertQuerySucceeded(settingsError, "Loading AI settings");
  assertQuerySucceeded(connectionError, "Loading channel capabilities");
  assertQuerySucceeded(messagesError, "Loading conversation messages");

  if (!settings) {
    throw new Error("Workspace AI settings are unavailable.");
  }
  if (!connection) {
    throw new Error("Conversation channel connection is unavailable.");
  }

  const messages = ((messageRows ?? []) as Record<string, unknown>[])
    .map(normalizeMessage)
    .reverse();
  const batchMessages = selectBatchMessages(messages);
  if (batchMessages.length === 0) {
    return null;
  }

  // Stage 6 will classify an unassigned batch through lib/ai. Until then we
  // deliberately use the already-assigned category, or the existing system
  // default category, without inventing a second classification path.
  const selectedCategory = selectCategoryForBatch(
    categories,
    batchMessages,
    input.messageId,
  );
  const knowledgeBase = buildKnowledgeBaseContext(
    knowledgeFiles satisfies KnowledgeFileRow[],
  );

  return {
    workspaceId: input.workspaceId,
    conversationId: input.conversationId,
    conversationKind: "dm",
    aiSettings: normalizeAiSettings(settings as Record<string, unknown>),
    messages,
    batchMessages,
    channelCapabilities: channelCapabilities(
      connection.platform,
      connection.capabilities,
    ),
    knowledgeBase,
    selectedCategory,
  };
}

function maskContext(context: LoadedDraftContext): MaskedDraftContext {
  const categoryInstruction = context.selectedCategory.draftInstruction ?? "";
  const values = [
    ...context.messages.map((message) => message.text),
    context.knowledgeBase.text,
    context.aiSettings.tone,
    context.aiSettings.language,
    context.aiSettings.signature,
    context.selectedCategory.name,
    context.selectedCategory.description,
    categoryInstruction,
  ];
  const { masked, entities } = maskMessages(values);
  let index = 0;
  const messages = context.messages.map((message) => ({
    ...message,
    text: masked[index++]!,
  }));
  const batchIds = new Set(context.batchMessages.map((message) => message.id));
  const batchMessages = messages.filter((message) => batchIds.has(message.id));
  const knowledgeBaseText = masked[index++]!;
  const tone = masked[index++]!;
  const language = masked[index++]!;
  const signature = masked[index++]!;
  const categoryName = masked[index++]!;
  const categoryDescription = masked[index++]!;
  const maskedCategoryInstruction = masked[index++]!;

  return {
    ...context,
    messages,
    batchMessages,
    aiSettings: { ...context.aiSettings, tone, language, signature },
    knowledgeBase: { ...context.knowledgeBase, text: knowledgeBaseText },
    selectedCategory: {
      ...context.selectedCategory,
      name: categoryName,
      description: categoryDescription,
      draftInstruction:
        context.selectedCategory.draftInstruction === null
          ? null
          : maskedCategoryInstruction,
    },
    entities,
  };
}

async function createGeneratingDraft(input: {
  context: LoadedDraftContext;
}): Promise<string> {
  const firstMessage = input.context.batchMessages[0];
  const lastMessage = input.context.batchMessages.at(-1);
  if (!firstMessage || !lastMessage) {
    throw new Error("Cannot create a draft for an empty message batch.");
  }

  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase
    .from("drafts")
    .insert({
      workspace_id: input.context.workspaceId,
      conversation_id: input.context.conversationId,
      first_message_id: firstMessage.id,
      last_message_id: lastMessage.id,
      status: "generating",
      kb_file_ids: input.context.knowledgeBase.usedFileIds,
    })
    .select("id")
    .single();
  assertQuerySucceeded(error, "Creating a generating draft");

  if (!data?.id) {
    throw new Error("Creating a generating draft returned no identifier.");
  }

  return data.id;
}

async function finalizeDraft(input: {
  workspaceId: string;
  draftId: string;
  text: string;
  model: string;
  supersedeEdited: boolean;
}): Promise<void> {
  const supabase = createAdminSupabaseClient();
  const { data, error } = await supabase.rpc("finalize_draft_generation", {
    target_workspace_id: input.workspaceId,
    target_draft_id: input.draftId,
    generated_text: input.text,
    generated_model: input.model,
    supersede_edited: input.supersedeEdited,
  });
  assertQuerySucceeded(error, "Finalizing a generated draft");

  if (data !== true) {
    throw new Error("The generating draft is no longer available to finalize.");
  }
}

export async function cleanupGeneratingDrafts(input: {
  workspaceId: string;
  conversationId: string;
  lastMessageId?: string;
}): Promise<void> {
  const supabase = createAdminSupabaseClient();
  let query = supabase
    .from("drafts")
    .delete()
    .eq("workspace_id", input.workspaceId)
    .eq("conversation_id", input.conversationId)
    .eq("status", "generating");

  if (input.lastMessageId) {
    query = query.eq("last_message_id", input.lastMessageId);
  }

  const { error } = await query;
  assertQuerySucceeded(error, "Cleaning up generating drafts");
}

export const draftPipelineDependencies: DraftPipelineDependencies = {
  loadDebounceSeconds,
  isLatestIncoming,
  loadContext,
  createGeneratingDraft,
  resolveModel: resolveGenerationModel,
  generate: (prompt, options) =>
    generateCompletion(prompt, {
      model: options.model,
      maxTokens: options.maxTokens,
      temperature: 0.3,
    }),
  finalizeDraft,
  cleanupGeneratingDrafts,
};

export async function runDraftPipeline(
  input: DraftPipelineInput,
  steps: DraftPipelineSteps,
  dependencies: DraftPipelineDependencies = draftPipelineDependencies,
  logger?: PromptLogger,
): Promise<DraftPipelineResult> {
  if (!input.regenerate) {
    if (!input.messageId) {
      return { status: "skipped", reason: "invalid-event" };
    }

    // Inngest v4's native debounce period is a static TimeStr, not a CEL
    // expression. The workspace-specific delay therefore uses a durable sleep,
    // followed by a last-event check; only the newest event can proceed.
    const debounceSeconds = await steps.run("load-debounce-settings", () =>
      dependencies.loadDebounceSeconds({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        messageId: input.messageId!,
      }),
    );
    if (debounceSeconds === null) {
      return { status: "skipped", reason: "invalid-event" };
    }

    await steps.sleep("workspace-debounce", `${debounceSeconds}s`);
    const isLatest = await steps.run("last-event-check", () =>
      dependencies.isLatestIncoming({
        workspaceId: input.workspaceId,
        conversationId: input.conversationId,
        messageId: input.messageId!,
      }),
    );
    if (!isLatest) {
      return { status: "skipped", reason: "superseded-event" };
    }
  }

  const context = await steps.run("load-context", () =>
    dependencies.loadContext(input),
  );
  if (!context) {
    return { status: "skipped", reason: "empty-batch" };
  }

  const stopReason = await steps.run("stop-check", () => {
    if (!input.regenerate && !context.aiSettings.autoGenerateDm) {
      return "auto-generation-disabled" as const;
    }
    if (context.selectedCategory.skipDraft) {
      return "category-skips-draft" as const;
    }
    return null;
  });
  if (stopReason) {
    return { status: "skipped", reason: stopReason };
  }

  const generationModel = dependencies.resolveModel(context.aiSettings.model);
  const maskedContext = await steps.run("mask", () => maskContext(context));
  const draftId = await steps.run("create-generating", () =>
    dependencies.createGeneratingDraft({ context }),
  );
  const completion = await steps.run("generate", async () => {
    const prompt = buildDraftPrompt({
      aiSettings: maskedContext.aiSettings,
      maskedMessages: maskedContext.messages.map((message) => ({
        direction: message.direction,
        text: message.text,
      })),
      channelCapabilities: maskedContext.channelCapabilities,
      conversationKind: maskedContext.conversationKind,
      knowledgeBase: maskedContext.knowledgeBase,
      selectedCategory: maskedContext.selectedCategory,
    });
    logPromptIfEnabled(prompt, logger ? { logger } : undefined);

    return dependencies.generate(prompt, {
      model: generationModel,
      maxTokens: DEFAULT_DRAFT_MAX_TOKENS,
    });
  });
  const restoredText = await steps.run("restore", () =>
    unmaskText(completion, maskedContext.entities),
  );

  await steps.run("finalize", () =>
    dependencies.finalizeDraft({
      workspaceId: input.workspaceId,
      draftId,
      text: restoredText,
      model: generationModel,
      supersedeEdited: input.regenerate,
    }),
  );

  // TODO(stage 9): emit the ID-only push event after draft readiness.
  return { status: "ready", draftId };
}
