import { describe, expect, it } from "vitest";

import {
  AI_LANGUAGE_MAX_LENGTH,
  AI_SIGNATURE_MAX_LENGTH,
  AI_TONE_MAX_LENGTH,
  validateAiSettingsInput,
  type AiSettingsInput,
} from "./settings";

const allowedModels = ["mistral-small-latest", "mistral-large-latest"];

function validInput(overrides: Partial<AiSettingsInput> = {}): AiSettingsInput {
  return {
    tone: "professional",
    language: "de",
    signature: "Viele Grüße",
    debounceSeconds: 60,
    model: "",
    autoGenerateDm: true,
    ...overrides,
  };
}

describe("validateAiSettingsInput", () => {
  it.each([0, 600])("accepts debounce boundary %i", (debounceSeconds) => {
    expect(
      validateAiSettingsInput(validInput({ debounceSeconds }), allowedModels),
    ).toMatchObject({ ok: true, data: { debounceSeconds } });
  });

  it.each([-1, 601, 45.5, Number.NaN])(
    "rejects invalid debounce %s",
    (debounceSeconds) => {
      expect(
        validateAiSettingsInput(validInput({ debounceSeconds }), allowedModels),
      ).toEqual({
        ok: false,
        error: "Дебаунс должен быть целым числом от 0 до 600 секунд.",
      });
    },
  );

  it("accepts auto and allowlisted models but rejects an unknown model", () => {
    expect(validateAiSettingsInput(validInput({ model: "" }), allowedModels).ok).toBe(
      true,
    );
    expect(
      validateAiSettingsInput(
        validInput({ model: "mistral-small-latest" }),
        allowedModels,
      ).ok,
    ).toBe(true);
    expect(
      validateAiSettingsInput(validInput({ model: "foreign-model" }), allowedModels),
    ).toEqual({ ok: false, error: "Выбранная модель недоступна." });
  });

  it("enforces text limits and normalizes surrounding whitespace", () => {
    expect(
      validateAiSettingsInput(
        validInput({ tone: " friendly ", language: " de ", signature: " Hi " }),
        allowedModels,
      ),
    ).toMatchObject({
      ok: true,
      data: { tone: "friendly", language: "de", signature: "Hi" },
    });

    for (const input of [
      validInput({ tone: "x".repeat(AI_TONE_MAX_LENGTH + 1) }),
      validInput({ language: "x".repeat(AI_LANGUAGE_MAX_LENGTH + 1) }),
      validInput({ signature: "x".repeat(AI_SIGNATURE_MAX_LENGTH + 1) }),
    ]) {
      expect(validateAiSettingsInput(input, allowedModels).ok).toBe(false);
    }
  });
});
