export const AI_TONE_MAX_LENGTH = 100;
export const AI_LANGUAGE_MAX_LENGTH = 50;
export const AI_SIGNATURE_MAX_LENGTH = 500;
export const AI_DEBOUNCE_MIN_SECONDS = 0;
export const AI_DEBOUNCE_MAX_SECONDS = 600;

export type AiSettingsInput = {
  tone: string;
  language: string;
  signature: string;
  debounceSeconds: number;
  model: string;
  autoGenerateDm: boolean;
};

export type AiSettingsValidationResult =
  | { ok: true; data: AiSettingsInput }
  | { ok: false; error: string };

function normalizeRequiredText(
  value: unknown,
  label: string,
  maxLength: number,
): { ok: true; value: string } | { ok: false; error: string } {
  if (typeof value !== "string") {
    return { ok: false, error: `${label}: введите текст.` };
  }

  const normalized = value.trim();

  if (!normalized) {
    return { ok: false, error: `${label}: поле не может быть пустым.` };
  }
  if (normalized.length > maxLength) {
    return {
      ok: false,
      error: `${label}: максимум ${maxLength} символов.`,
    };
  }

  return { ok: true, value: normalized };
}

export function validateAiSettingsInput(
  input: AiSettingsInput,
  allowedModels: readonly string[],
): AiSettingsValidationResult {
  const tone = normalizeRequiredText(
    input.tone,
    "Тон ответов",
    AI_TONE_MAX_LENGTH,
  );
  if (!tone.ok) {
    return tone;
  }

  const language = normalizeRequiredText(
    input.language,
    "Язык ответов",
    AI_LANGUAGE_MAX_LENGTH,
  );
  if (!language.ok) {
    return language;
  }

  if (typeof input.signature !== "string") {
    return { ok: false, error: "Подпись: введите текст." };
  }
  const signature = input.signature.trim();
  if (signature.length > AI_SIGNATURE_MAX_LENGTH) {
    return {
      ok: false,
      error: `Подпись: максимум ${AI_SIGNATURE_MAX_LENGTH} символов.`,
    };
  }

  if (
    !Number.isInteger(input.debounceSeconds) ||
    input.debounceSeconds < AI_DEBOUNCE_MIN_SECONDS ||
    input.debounceSeconds > AI_DEBOUNCE_MAX_SECONDS
  ) {
    return {
      ok: false,
      error: `Дебаунс должен быть целым числом от ${AI_DEBOUNCE_MIN_SECONDS} до ${AI_DEBOUNCE_MAX_SECONDS} секунд.`,
    };
  }

  if (typeof input.autoGenerateDm !== "boolean") {
    return { ok: false, error: "Некорректная настройка авто-генерации для сообщений." };
  }

  if (typeof input.model !== "string") {
    return { ok: false, error: "Выберите модель из списка." };
  }
  const model = input.model.trim();
  if (model && !allowedModels.includes(model)) {
    return { ok: false, error: "Выбранная модель недоступна." };
  }

  return {
    ok: true,
    data: {
      tone: tone.value,
      language: language.value,
      signature,
      debounceSeconds: input.debounceSeconds,
      model,
      autoGenerateDm: input.autoGenerateDm,
    },
  };
}
